<ins class="clear space-small"></ins>

<div class="dd">
	<div id="foot-service" class="dd50">
		<span>Usługi:</span>
		<?php print $this->catalogService()->render('_partial/catalogServiceFoot.phtml') ?>
	</div>
	<div id="foot-options" class="dd50">
		<span>Gabinet zapewnia:</span>
		<?php print $this->catalogOptions()->render('_partial/catalogOptionsFoot.phtml') ?>
	</div>
</div>

<ins class="clear space-small"></ins>
