<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<?php
	print $this->headBase();
    print $this->headMeta();
    print $this->headTitle();
    print $this->headScript();
    print $this->headLink();
    print $this->headStyle();
?>
</head>

<body>
   <div id="wrapper" class="home">
   		<?php print $this->partial('_partial/head.phtml')?>
   		
        <div id="container">
       	  <div class="column c66">
                <div class="inner">
                	<?php print $this->layout()->content ?>
                </div>
            </div>
            <div class="column c33 sidebar"><div class="inner">
            	<div class="pale">
            		<?php print $this->catalogPremium()
							 ->setRandom(true)
							 ->setRowCount(7)
							 ->render('_partial/catalogPremium.phtml')?>

                    <b class="lt"></b><b class="lb"></b><b class="rt"></b><b class="rb"></b>
                </div>
                
            </div></div>
        </div>
        
        <div id="footer">
        	<?php print $this->partial('_partial/foot.phtml')?>
        </div>

        <div id="bottom">
        	<?php print $this->partial('_partial/bottom.phtml')?>
        </div>
   </div>
</body>

<?php print htmlspecialchars_decode($this->inlineScript())?>
</html>