<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<?php
	print $this->headBase();
    print $this->headMeta();
    print $this->headTitle();
    print $this->headScript();
    print $this->headLink();
    print $this->headStyle();
?>
</head>

<body>
   <div id="wrapper" class="home">
   		<?php print $this->partial('_partial/head.phtml')?>
   		
		<div id="bar">
        	<h3 class="h-img wybranysalon">Wybrany salon</h3>
            <h1><?php print $this->escape(@$this->catalogRow->name) ?></h1>
            <ul>
            	<li <?php print $this->tab == 'ogolne' ? 'class="active"' : null; ?>><a class="ogn" href="<?php print $this->url(array('tab'=>'ogolne'));?>"><span>Ogólne</span></a></li>
			<li <?php print $this->tab == 'uslugi' ? 'class="active"' : null; ?>><a class="usg" href="<?php print $this->url(array('tab'=>'uslugi'));?>"><span>Usługi</span></a></li>
			<li <?php print $this->tab == 'personel' ? 'class="active"' : null; ?>><a class="psn" href="<?php print $this->url(array('tab'=>'personel'));?>"><span>Personel</span></a></li>
            </ul>
        </div>
   		
        <div id="container">
       	  <div class="column c66 darkpale">
                <div class="inner">
                	<?php print $this->layout()->content ?>
                </div>
            </div>
            <div class="column c33 sidebar"><div class="inner">
            	<div id="google-map" class="pale">
                    <h3 class="h-img mapadojazdu">Mapa dojazdu</h3>
					<dir id="googleMaps" class="small"></dir>
                    <b class="lt"></b><b class="lb"></b><b class="rt"></b><b class="rb"></b>
                </div>
                
                
                <?php if (count(@$this->imagesRowset)):?>
				<div id="carousel" class="pale">
					<a href="#" class="previous">poprzednie</a>
					<a href="#" class="next">następne</a>
					<ul class="jcarousel">
						<?php foreach ((array)@$this->imagesRowset as $image):?>
						<?php if ($image['id'] != $this->catalogRow['catalog_image_id']):?>
						<li><a rel="viz" class="colorbox" href="/upload/catalog/image/full/<?php print $this->escape($image['image'])?>"><img src="/upload/catalog/image/thumb1/<?php print $this->escape(@$image['image'])?>" /></a></li>
						<?php endif;?>
						<?php endforeach;?>
					</ul>
					<b class="lt"></b><b class="lb"></b><b class="rt"></b><b class="rb"></b>
				</div>
				<?php endif;?>
                
            </div></div>
        </div>
        
        <div id="footer">
        	<?php print $this->partial('_partial/foot.phtml')?>
        </div>

        <div id="bottom">
        	<?php print $this->partial('_partial/bottom.phtml')?>
        </div>
   </div>
</body>

<?php print htmlspecialchars_decode($this->inlineScript())?>
</html>