<?php print $this->doctype(); ?>
<html>
<head>
	<?php
		print $this->headBase();
    	print $this->headMeta();
    	print $this->headTitle();
    	print $this->headScript();
    	print $this->headLink();
    	print $this->headStyle();
    ?>
</head>
<body>
<div id="wrapper">

	<div class="ads">
		<script type='text/javascript'><!--// <![CDATA[
			OA_show(9);
		// ]]> --></script>
	</div>

	<div id="header">
		<?php print $this->partial('_partial/head.phtml')?>

		<ul id="subnav" class="usluga">
			<li class="first"><h1><?php print $this->escape(@$this->row['name']) ?></h1></li>
		</ul>
	</div>

	<div id="content">
		<!-- Kolumna 1 - lewa -->
		<div class="col c1 wide">
			<?php print $this->layout()->content ?>
		</div>
		
		<!-- Kolumna 2 - prawa -->
		<div class="col">
		
			<div class="ads">
				<script type='text/javascript'><!--// <![CDATA[
					OA_show(10);
				// ]]> --></script>
			</div>
			
			<div class="c3">
				<?php print $this->catalogPremium()
								 ->setRandom(true)
								 ->setRowCount(6)
								 ->render('_partial/catalogPremium.phtml')?>
			</div>
		</div>
	</div>

	<div class="doubleLine"></div>
	<div id="footer">
		<?php print $this->partial('_partial/foot.phtml')?>
		<?php print $this->partial('_partial/footSub.phtml')?>
	</div>

</div>
<?php print htmlspecialchars_decode($this->inlineScript())?>
</body>
</html>
