<?php print $this->doctype(); ?>
<html>
<head>
	<?php
		print $this->headBase();
    	print $this->headMeta();
    	print $this->headTitle();
    	print $this->headScript();
    	print $this->headLink();
    	print $this->headStyle();
    ?>
</head>
<body>
<div id="wrapper">

	<script type='text/javascript'><!--// <![CDATA[
		OA_show(9);
	// ]]> --></script>

	<div id="header">
		<?php print $this->partial('_partial/head.phtml')?>
	</div>

	<div id="content">
		<div id="loader">Wczytuję, prosze czekać..</div>

		<!-- Kolumna 1 - lewa -->
		<div class="col c1 wide">
			<div class="inner">
				<form action="<?php print $this->url(array(),'catalog-search');?>" method="get" id="bigSerchForm">
					<input type="text" class="text" id="fraza" name="q" value="<?php print $this->escape(strip_tags($this->q))?>" />
					<input type="image" class="submit" id="szukaj-weterynarza" />
				</form>
			</div>
			
			<div class="indent">
				<?php print $this->page('jak-szukac','_partial/page.phtml')?>
			</div>
			
			<?php print $this->layout()->content ?>
			
		</div>
		
		<!-- Kolumna 3 - prawa -->
		<div class="col">
		
			<div class="ads">
				<script type='text/javascript'><!--// <![CDATA[
					OA_show(10);
				// ]]> --></script>
			</div>
			
			<div class="c3">
				<?php print $this->catalogPremium()
								 ->setRandom(true)
								 ->setRowCount(6)
								 ->render('_partial/catalogPremium.phtml')?>
			</div>
		</div>
	</div>

	<div class="doubleLine"></div>
	<div id="footer">
		<?php print $this->partial('_partial/foot.phtml')?>
		<?php print $this->partial('_partial/footSub.phtml')?>
	</div>

</div>
<?php print $this->inlineScript()?>
</body>
</html>
