<div class="span-18 options-holder">
	<?= $this->partial('_partial/common_head.phtml', array('controller' => 'language','action'=>'edit')) ?>
</div>
<div class="span-4 last options-holder">
	<ul class="options-list top-right">
		<li><a title="Dodaj język" class="action add" href="<?php
	    	print $this->url(array(
	  			'module'=>'language',
	  			'controller'=>'admin',
	  			'action'=>'add'
    		));
	    ?>">Dodaj język</a></li>
	</ul>
</div>

<hr class="bottom"/>
<?php print $this->form ?>