<div class="span-24 last options-holder">
	<?php print $this->partial('_partial/common_head.phtml', array('controller' => 'staff')) ?>
</div>

<hr class="bottom"/>

<div class="span-2 options-holder">
	<h3>Akcje:</h3>
</div>

<div class="span-20 last options-holder">
	<ul class="options-list top-left">
		 <li><a title="Dodaj osobę" class="action add" href="<?php print $this->url(array(
                   'module' => 'catalog',
                   'controller'=>'staff',
                   'action'=>'add'
                ),'default',false,false); ?>">Dodaj osobę</a></li>
	</ul>
</div>

<hr class="bottom"/>

<form method="get" action="<?php print $this->actionUrl ?><?php print $this->valuesQuery?>">
    <?php print $this->dataGrid($this->grid, '_partial/newDataGrid.phtml');?>
</form>