<div class="span-19 options-holder">
	<?= $this->partial('_partial/common_head.phtml', array('controller' => 'block')) ?>
</div>
<div class="span-3 last options-holder">
	<ul class="options-list top-right">
		<li><a title="Dodaj blok tekstu" class="action add" href="<?php
	    	print $this->url(array(
	  			'module'=>'page',
	  			'controller'=>'block',
	  			'action'=>'add',
    		), 'default');
	    ?>">Dodaj blok tekstu</a></li>
	</ul>
</div>

<hr class="bottom"/>

<div class="box text-right">
	<?= $pagination = $this->paginationControl($this->paginator, 'Sliding','_partial/pagination.phtml'); ?>
</div>

<hr class="bottom"/>

<table>
  <col span="2"/>
  <col class="even" span="2"/>
 <thead>
  <tr>
    <th>Nazwa</th>
    <th>Strona</th>
    <th class="span-1">&nbsp;</th>
    <th class="span-1">&nbsp;</th>
  </tr>
 </thead>
 <tbody>
  <?php if(count($this->rowset) < 1): ?>

   <tr>
    <td colspan="4"><p class="msg-notice bottom">Brak rekordów</p></td>
   </tr>

  <?php else: ?>

  <?php foreach ($this->rowset as $row): ?>
  <tr>
    <td><a href="<?php
    	print $this->url(
    		array(
	  			'module'=>'page',
	  			'controller'=>'block',
	  			'action'=>'edit',
	  			'id' => $row->id
    		),'default'
    	);
    ?>"><?php print $row->block_id ?></a></td>
    <td><a href="<?php
    	print $this->url(
    		array(
	  			'module'=>'page',
	  			'controller'=>'page',
	  			'action'=>'edit',
	  			'id' => $row->page_id
    		),'default'
    	);
    ?>"><?php print $row->page_id ?></a></td>
    <td><a class="action edit small" href="<?php
    	print $this->url(
    		array(
	  			'module'=>'page',
	  			'controller'=>'block',
	  			'action'=>'edit',
	  			'id' => $row->id
    		),'default'
    	);
    ?>">edytuj</a></td>
    <td class="center"><a
    	title="Usuń"
    	onclick="return confirm('Czy usunąć rekord?');"
    	class="action trash ico small" href="<?php
    	print $this->url(
    		array(
	  			'module'=>'page',
	  			'controller'=>'block',
	  			'action'=>'delete',
	  			'id' => $row->id
    		),'default'
    	);
    ?>">usuń</a></td>
  </tr>
  <?php endforeach; ?>

  <?php endif; ?>
 </tbody>
</table>

<div class="box text-right">
	<?= $pagination = $this->paginationControl($this->paginator, 'Sliding','_partial/pagination.phtml'); ?>
</div>
