<?php print $this->doctype(); ?>
<html>
<head>
	<?php
		print $this->headBase();
    	print $this->headMeta();
    	print $this->headTitle();
    	print $this->headScript();
    	print $this->headLink();
    	print $this->headStyle();
    ?>
</head>
<body>

<div id="top">
	<div class="container">
		<?php print $this->partial('_partial/head.phtml') ?>
	</div>
</div>

<div class="container">

	<div class="span-17" id="main">
		<div class="news-rowset">
		<?php print $this->partial('_partial/messages.phtml',array('messages' => $this->messages)) ?>
		<?php print $this->layout()->content ?>
		</div>
	</div>

	<div class="span-7 last" id="panel">
		<div id="news-timeline">
			<?php print $this->timeRange(null)->__toString() ?>
		</div>
		<div id="news-category">
			<?php //print $this->TreeCategoryAnchor(null, $this->category_url) ?>
		</div>
	</div>

	<?php print $this->partial('_partial/foot.phtml') ?>

</div>
</body>
</html>