<?php print $this->doctype(); ?>
<html>
<head>
	<?php
		print $this->headBase();
    	print $this->headMeta();
    	print $this->headTitle();
    	print $this->headScript();
    	print $this->headLink();
    	print $this->headStyle();
    ?>
</head>
<body>

<div id="top">
	<div class="container">
		<?php print $this->partial('_partial/head.phtml') ?>
	</div>
</div>

<div class="container">

	<div class="span-17" id="main">
		<?php print $this->partial('_partial/messages.phtml',array('messages' => $this->messages)) ?>
		<?php print $this->layout()->content ?>
	</div>

	<div class="span-7 last" id="panel">
		<h3>Twoje profil</h3>
		<ul>
			<li><a href="<?= $this->url(array('controller'=>'user','action'=>'personal')) ?>">Dane osobowe</a></li>
			<!-- 
			<li><a href="<?= $this->url(array('controller'=>'user','action'=>'avatar')) ?>">Fotografia</a></li>
			 -->
			<li><a href="<?= $this->url(array('controller'=>'user','action'=>'group')) ?>">Twoje klasy</a></li>
			<li><a href="<?= $this->url(array('controller'=>'user','action'=>'password'))?>">Zmień hasło</a></li>
		</ul>
	</div>

	<?php print $this->partial('_partial/foot.phtml') ?>

</div>
</body>
</html>