<h2>Aktualizacja rekordu!</h2>
<p>Dodawaj zdjęcia, informacje o usługach i godzinach przyjęć.
Pamiętaj! Czym więcej informacji posiada Twoja wizytówka tym wyżej 
znajduje się w spisie!</p>

Uzupełnij swój profil na 3 sposoby:

<ul style="list-style: decimal;">
	<li>Wypełnij elektroniczne zgłoszenie</li>
	<li>Pobierz formularz zgłoszenia do druku i wyślij faksem na nr (012) 429 45 86</li>
	<li>Pobierz formularz zgłoszenia, wypełnij i odeślij mailem na adres: <a href="mailto:zgloszenie@stomatolodzy.krakow.pl">zgloszenie@stomatolodzy.krakow.pl</a></li>
</ul> 