<?php 
if (count($this->row)) {
	if (strlen($this->row['meta_title']) > 1) {
		$this->headTitle($this->row['meta_title']);
	}
	if (strlen($this->row['meta_description']) > 1) {
		$this->headMeta($this->row['meta_description'], 'description');
	}
	if (strlen($this->row['meta_keywords']) > 1) {
		$this->headMeta($this->row['meta_keywords'], 'keywords');
	}
}
?>

<ul id="people-container">
	<?php print $this->partialLoop('_partial/partialLoopCatalogList.phtml', (array) $this->rowset)?>
</ul>

<?php
if (null != $this->paginator) {
	/* @var $paginationControl Zend_View_Helper_PaginationControl */
	$paginationControl = $this->getHelper('PaginationControl');
	
	print $paginationControl->paginationControl($this->paginator,
                             'Sliding',
                             '_partial/newPagination.phtml');
}
?>