<ul id="promofoot">
  <li>
  	<a href="http://weterynarze.krakow.pl/" title="Weterynarze w Krakowie"><img src="http://weterynarze.krakow.pl/images/weterynarze/logo_32x32.png" width="24" height="24" alt="weterynarze Kraków" /></a>
  	<a href="http://weterynarze.krakow.pl/" title="Weterynarz w Krakowie">Weterynarz Kraków</a>
  </li>
  <li>
  	<a href="http://lekarze.krakow.pl/" title="Zdrowie w Krakowie"><img src="http://lekarze.krakow.pl/images/lekarze/logo_32x32.png" width="24" height="24" alt="lekarz kraków" /></a>
  	<a href="http://lekarze.krakow.pl/" title="Lekarze w Krakowie">Lekarz Kraków</a>
  </li>
  <li>
  	<a href="http://stomatolodzy.krakow.pl/" title="Kliknij i zobacz najlepszych stomatologów w Krakowie!"><img src="http://stomatolodzy.krakow.pl/images/stomatolodzy/logo_32x32.png" width="24" height="24" alt="dentysta kraków" /></a>
  	<a href="http://stomatolodzy.krakow.pl/" title="Kliknij i zobacz najlepszych stomatologów w Krakowie">Stomatolog Kraków</a>
  </li>
</ul>

<p class="small">Mapy udostępnione przez <a href="http://google.pl">Google.pl</a></p>