<?php foreach ((array) $this->rowset as $row):?>
<?php if (strlen(@$row['alias']) > 1):?>
<a href="<?php print $this->url(array('alias' => $row['alias']), 'catalogOptionsWww')?>"><?php print $this->escape($row['name'])?></a>
<?php else:?>
<a href="<?php print $this->url(array('id' => $row['id']), 'catalog-options')?>"><?php print $this->escape($row['name'])?></a>
<?php endif;?>
<?php endforeach;?>
