<span class="footline"><a href="<?php print $this->url(array('url' => 'porady-prawne'),'page-page',true) ?>">porady prawne!</a></span>
<ul>
	<li><a href="<?php print $this->url(array(),'catalog-main',true) ?>">Strona Główna</a></li>
	<li><a href="<?php print $this->url(array('url' => 'informacje-dla-prawnikow'),'page-page',true) ?>">Informacje dla prawników</a></li>
	<li><a href="<?php print $this->url(array('url' => 'reklama'),'page-page',true) ?>">Reklama</a></li>
	<li><a href="<?php print $this->url(array('url' => 'polityka-prywatnosci'),'page-page',true) ?>">Polityka prywatności</a></li>
	<li><a href="<?php print $this->url(array('url' => 'kontakt'),'page-page',true) ?>">Kontakt</a></li>
</ul>