<div class="dd">
	<div id="foot-service" class="dd50">
		<span>Usługi:</span>
		<?php print $this->catalogService()->render('_partial/catalogServiceFoot.phtml') ?>
	</div>
	<div id="foot-options" class="dd50">
		<span>Zapewniamy:</span>
		<?php print $this->catalogOptions()->render('_partial/catalogOptionsFoot.phtml') ?>
	</div>
	<div id="foot-type" class="dd50">
		<span>Rodzaj gabinetu:</span>
		<?php print $this->catalogType()->render('_partial/catalogTypeFoot.phtml') ?>
	</div>
</div>