<div class="span-22 last options-holder">
	<?= $this->partial('_partial/common_head.phtml', array('controller' => 'catalog')) ?>
</div>

<hr class="bottom"/>

<div class="span-2 options-holder">
	<h3>Akcje:</h3>
</div>

<div class="span-20 last options-holder">
	<ul class="options-list top-left">
		<li><a title="Dodaj wpis" class="action add" href="<?php
	    	print $this->url(array(
	    		'module' => 'catalog',
	  			'controller'=>'catalog',
	  			'action'=>'add'
    		),'default',false,false);
	    ?>">Dodaj wpis</a></li>
	</ul>

	<ul class="options-list top-right">
		<li>
			<a class="action trash small" href="<?php print $this->url(array(
			'module' => 'catalog',
			'controller' => 'catalog',
			'action' => 'clearcache'
			)); ?>">Wyczyść cache</a>
		</li>
		<li>
			<a class="action trash small" href="<?php print $this->url(array(
			'module' => 'catalog',
			'controller' => 'list',
			'action' => 'cleargmapcache'
			)); ?>">Wyczyść cache mapy</a>
		</li>
		<li>
			<a class="action web small" href="<?php print $this->url(array(
			'module' => 'catalog',
			'controller' => 'list',
			'action' => 'kml'
			)); ?>">KML dla Google</a>
		</li>
	</ul>
</div>

<hr class="bottom"/>

<form method="get" action="<?php print $this->actionUrl ?><?php print $this->valuesQuery?>">
<?php
	print $this->dataGrid($this->grid, '_partial/dataGrid.phtml');
?>
</form>