<h2>Panel administracyjny</h2>
<hr class="bottom"/>

<div class="span-5 colborder">
	<h3>Opcjie systemowe</h3>

	<div class="span-5 last">
		<p><a class="action big user" href="<?php print $this->url(array('module' => 'user', 'controller' => 'admin', 'action' => 'index'),'default',true); ?>">Użytkowik</a></p>
		<p class="">Użytkownicy prawa dostępu</p>
	</div>

	<hr/>

	<div class="span-5 last">
		<p><a class="action big settings" href="<?php print $this->url(array('module' => 'system', 'controller' => 'admin', 'action' => 'index'),'default',true); ?>">System</a></p>
		<p>Konfiguracja systemu! <em>OSTROŻNIE!</em></p>
	</div>
</div>
<div class="span-18 last">
	<h3>Podstawowe opcje zarządzania stroną internetową</h3>

	<div class="span-9">
		<p><a class="action big content" href="<?php print $this->url(array('module' => 'page', 'controller' => 'admin', 'action' => 'index'),'default',true); ?>">Treść</a></p>
		<p>Zarządzanie stronami i blokami tekstu</p>
	</div>
	<div class="span-9 last">
		<p><a class="action big folder" href="<?php print $this->url(array('module' => 'catalog', 'controller' => 'admin', 'action' => 'index'),'default',true); ?>">Katalog</a></p>
		<p>Zarządzanie wpisami wizytówke, promocją wpisów oraz inne zaawansowane opcje jak np. zarządzanie wynikami wyszukiwania</p>
	</div>
	
	<hr/>
	
	<div class="span-9">
		<p><a class="action big rss" href="<?php print $this->url(array('module' => 'agregator', 'controller' => 'agregator', 'action' => 'list'),'default',true); ?>">Agregator RSS</a></p>
		<p>Agregator treści RSS biera i zapisuje treści dostępne poprzez kanał wiadomosci RSS</p>
	</div>
	
	<hr/>

	<h3>Monitoring/Promocja</h3>
	
	<div class="span-9">
		<p><a class="action big stats" href="http://ads.eu1.pl">Reklama (www.ads.eu1.pl)</a></p>
		<p>Reklamodawcy, miejsca reklamowe</p>
	</div>
	<div class="span-9 last">
		<p><a class="action big stats-3" href="http://clickheat.eu1.pl/">Monitoring kliknięć (clickheat.eu1.pl)</a></p>
		<p>Sprawdzanie usability, jak użytkownik reaguje/zachowuje się na stronie</p>
	</div>
</div>