<?php $url = $this->getHelper('url')?>

<?php if (count($this->rowset)):?>

<?php 
$data = array_merge($this->rowset, $this->rowset, $this->rowset);
?>
<ul id="newPremium" class="aircycle">
<?php foreach ((array) $data as $row):?>
	<li class="row <?php print $this->cycle(array('odd','even'))?>">
		<a href="<?php print $url->url(array('id' => $row['id']), 'catalog-show'); ?>">
			<?php print $this->escape($row['name'])?></a>
	</li>
<?php endforeach;?>
</ul>
<?php endif;?>

<script type="text/javascript">
<!--
(function($) {
	$.fn.airCycle = function(settings) 
	{
		var config = {'foo': 'bar'};
		if (settings) $.extend(config, settings);

		this.each(function(){
			
		});

		return this;
	};
})(jQuery);

$('#newPremium').airCycle();
//-->
</script>