<p class="copyright"><a href="<?php print $this->url(array('url' => 'jak-zadbac-o-swoje-zeby'),'page-page',true) ?>">Jak zadbać o swoje zęby!</a></p>

<ul>
	<li>&#9642; <a href="<?php print $this->url(array(),'catalog-main',true) ?>">Strona Główna</a></li>
	<li>&#9642; <a href="<?php print $this->url(array('url' => 'informacje-dla-stomatologow'),'page-page',true) ?>" title="Informacje dla stomatologów">Informacje dla stomatologów</a></li>
	<li>&#9642; <a href="<?php print $this->url(array('url' => 'reklama'),'page-page',true) ?>">Reklama</a></li>
	<li>&#9642; <a href="<?php print $this->url(array('url' => 'polityka-prywatnosci'),'page-page',true) ?>">Polityka Prywatności</a></li>
	<li>&#9642; <a href="<?php print $this->url(array('url' => 'kontakt'),'page-page',true) ?>">Kontakt</a></li>
</ul>

<ins class="clear space-small"></ins>

<ul id="promofoot">
  <li>
  	<a href="http://prawnicy.krakow.pl/" title="Notariusz w Krakowie"><img src="http://prawnicy.krakow.pl/images/prawnicy/logo_32x32.png" width="24" height="24" alt="notariusz kraków" /></a>
  	<a href="http://prawnicy.krakow.pl/" title="Prawnik w Krakowie">Prawnik Kraków</a>
  </li>
  <li>
  	<a href="http://weterynarze.krakow.pl/" title="Weterynarze w Krakowie"><img src="http://weterynarze.krakow.pl/images/weterynarze/logo_32x32.png" width="24" height="24" alt="weterynarze Kraków" /></a>
  	<a href="http://weterynarze.krakow.pl/" title="Weterynarz w Krakowie">Weterynarz Kraków</a>
  </li>
  <li>
  	<a href="http://lekarze.krakow.pl/" title="Zdrowie w Krakowie"><img src="http://lekarze.krakow.pl/images/lekarze/logo_32x32.png" width="24" height="24" alt="lekarz kraków" /></a>
  	<a href="http://lekarze.krakow.pl/" title="Lekarze w Krakowie">Lekarz Kraków</a>
  </li>
  <li>
  	<a href="http://fryzjerzy.krakow.pl/" title="Dobry fryzjer Kraków!"><img src="http://fryzjerzy.krakow.pl/images/fryzjerzy/logo_32x32.png" width="24" height="24" alt="fryzjer kraków" /></a>
  	<a href="http://fryzjerzy.krakow.pl/" title="Studio urody">Studio urody Kraków</a>
  </li>
</ul>

<p class="small">Mapy udostępnione przez <a href="http://google.pl">Google.pl</a></p>

<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
try {
var pageTracker = _gat._getTracker("UA-7556328-1");
pageTracker._trackPageview();
} catch(err) {}</script>

