<table class="kontorx_dataorder">
	<thead>
		<tr>
			<?php foreach ($this->columns as $column): ?>
			<th class="<?php print $column->class ?>" rowspan="<?php print $column->rowspan ?>" style="<?php print $column->style ?>"><?php print $column ?></th>
			<?php endforeach; ?>
		</tr>
		<tr class="filters">
			<?php foreach ($this->filters as $filters): ?>
			<th>
				<?php foreach ($filters as $filter): ?>
				<span class="filter"><?php print $filter?></span>
				<?php endforeach; ?>
			</th>
			<?php endforeach; ?>
		</tr>
	</thead>
	<tbody>
		<?php $this->rowset->rewind()?>
		<?php foreach ($this->rowset as $cellset): ?>
		<?php if ($cellset->hasGroupedCell()): ?>
		<tr class="groupColumn <?php print $this->cycle(array('odd','even'))?>">
			<td colspan="<?php print count($cellset)?>"><?php
				print $cellset->getGroupCell();
			?></td>
		</tr>
		<?php endif; ?>

		<tr class="<?php print $this->cycle(array('odd','even'))?>">
			<?php foreach ($cellset as $cell): ?>
			<td><?php print $cell;?></td>
			<?php endforeach; ?>
		</tr>
		
		<?php endforeach; ?>
	</tbody>
	<tfoot>
		<tr>
			<td colspan="<?php print count($this->columns) ?>">
				<?php if ($this->paginator): ?>
				<?php print $this->paginationControl($this->paginator, 'Sliding','_partial/pagination.phtml', array('valuesQuery' => $this->valuesQuery)); ?>
				<?php endif;?>
			</td>
		</tr>
	</tfoot>
</table>