<h3>Zaawansowane opcje wyszukiwania</h3>

<ul>
	<li><a href="<?php print $this->url(array('controller' => 'searchfind', 'action' => 'list')); ?>">Sprawdz 1</a></li>
	<li><a href="<?php print $this->url(array('controller' => 'searching', 'action' => 'list')); ?>">Sprawdz 1</a></li>
	<li><a href="<?php print $this->url(array('controller' => 'searchquery', 'action' => 'list')); ?>">Sprawdz 1</a></li>
	<li>
		<a href="<?php print $this->url(array('action' => 'generate')); ?>">Generator</a>
		<p class="small">Stara opcja, może służyć jako monitoring czy wszystko jest poprawnie generowane dla semantyczneego wyszukiwania</p>
	</li>
</ul>