<?php $this->headTitle($this->q)?>

<?php $url = $this->getHelper('Url');?>
<?php foreach ((array) $this->rowset as $row):?>
<?php switch (@$row['catalog_promo_type_id']):?>
<?php case '3':?>
<div class="offerBox premium">
	<?php if(strlen(@$row['image']) > 2):?>
	<a href="<?php print $url->url(array('id' => $row['id']), 'catalog-show'); ?>">
		<img src="/upload/catalog/image/logo/<?php print $this->escape($row['image'])?>" alt="Logo: <?php print $this->escape($row['name'])?>" class="offerLogo" /></a>
	<?php endif;?>

	<p class="breadcrumb"><a href="<?php print $url->url(array('id' => $row['id']), 'catalog-show'); ?>">zobacz więcej &raquo; </a></p>
	<h4><a href="<?php print $url->url(array('id' => $row['id']), 'catalog-show'); ?>"><?php print $this->escape($row['name'])?></a></h4>
	<p class="address">
		<a href="<?php print $this->url(array('url' => $row['district_url']),'catalog-category',true)?>"><?php print $row['district']?></a>, 
		<a href="/szukaj?q=<?php print $this->escape($row['adress'])?>"><?php print $this->escape($row['adress'])?></a></p>
	
	<ul>
		<?php if(strlen(@$row['option1']) > 2):?>
		<li><a href="<?php print $url->url(array('id' => $row['id']), 'catalog-show'); ?>"><?php print $row['option1']?></a></li>
		<?php endif;?>
		<?php if(strlen(@$row['option2']) > 2):?>
		<li><a href="<?php print $url->url(array('id' => $row['id']), 'catalog-show'); ?>"><?php print $row['option2']?></a></li>
		<?php endif;?>
		<?php if(strlen(@$row['option3']) > 2):?>
		<li><a href="<?php print $url->url(array('id' => $row['id']), 'catalog-show'); ?>"><?php print $row['option3']?></a></li>
		<?php endif;?>
	</ul>
	<img class="mapRank" src="css/newlekarze/img/gmap/marker-premium.png" alt="" />
</div>
<?php break;?>

<?php case '2':?>
<div class="offerBox medium">
	<?php if(strlen(@$row['image']) > 2):?>
	<a href="<?php print $url->url(array('id' => $row['id']), 'catalog-show'); ?>">
		<img src="/upload/catalog/image/logo/<?php print $this->escape($row['image'])?>" alt="Logo: <?php print $this->escape($row['name'])?>" class="offerLogo" /></a>
	<?php endif;?>

	<p class="breadcrumb"><a href="<?php print $url->url(array('id' => $row['id']), 'catalog-show'); ?>">zobacz więcej &raquo; </a></p>
	<h4><a href="<?php print $url->url(array('id' => $row['id']), 'catalog-show'); ?>"><?php print $this->escape($row['name'])?></a></h4>
	<p class="address">
		<a href="<?php print $this->url(array('url' => $row['district_url']),'catalog-category',true)?>"><?php print $row['district']?></a>, 
		<a href="/szukaj?q=<?php print $this->escape($row['adress'])?>"><?php print $this->escape($row['adress'])?></a></p>
	<img class="mapRank" src="css/newlekarze/img/gmap/marker-medium.png" alt="" />
</div>
<?php break;?>

<?php case '1':?>
<div class="offerBox standard">
	<?php if(strlen(@$row['image']) > 2):?>
	<a href="<?php print $url->url(array('id' => $row['id']), 'catalog-show'); ?>">
		<img src="/upload/catalog/image/logo/<?php print $this->escape($row['image'])?>" alt="Logo: <?php print $this->escape($row['name'])?>" class="offerLogo" /></a>
	<?php endif;?>

	<p class="breadcrumb"><a href="<?php print $url->url(array('id' => $row['id']), 'catalog-show'); ?>">zobacz więcej &raquo; </a></p>
	<h4><a href="<?php print $url->url(array('id' => $row['id']), 'catalog-show'); ?>"><?php print $this->escape($row['name'])?></a></h4>
	<p class="address">
		<a href="<?php print $this->url(array('url' => $row['district_url']),'catalog-category',true)?>"><?php print $row['district']?></a>,
		<a href="/szukaj?q=<?php print $this->escape($row['adress'])?>"><?php print $this->escape($row['adress'])?></a></p>
	<img class="mapRank" src="css/newlekarze/img/gmap/marker-standard.png" alt="" />
</div>
<?php break;?>
<?php default:?>
<div class="offerBox standard">
	<p class="breadcrumb"><a href="<?php print $url->url(array('id' => $row['id']), 'catalog-show'); ?>">zobacz więcej &raquo; </a></p>
	<h4><a href="<?php print $url->url(array('id' => $row['id']), 'catalog-show'); ?>"><?php print $this->escape($row['name'])?></a></h4>
	<p class="address">
		<a href="<?php print $this->url(array('url' => $row['district_url']),'catalog-category',true)?>"><?php print $row['district']?></a>,
		<a href="/szukaj?q=<?php print $this->escape($row['adress'])?>"><?php print $this->escape($row['adress'])?></a></p>
	<img class="mapRank" src="css/newlekarze/img/gmap/marker-default.png" alt="" />
</div>
<?php break;?>
<?php endswitch;?>
<?php endforeach;?>

<?php
if (null != $this->paginator) {
	print $this->paginationControl($this->paginator,
                             'Sliding',
                             '_partial/newPaginationSearch.phtml');
}
?>