<div class="span-18 options-holder">
	<?= $this->partial('_partial/common_head.phtml', array('controller' => 'user')) ?>
</div>
<div class="span-4 last options-holder">
	<ul class="options-list top-right">
		<li><a title="Dodaj uzytkownika" class="action add" href="<?php
	    	print $this->url(array(
	  			'module'=>'user',
	  			'controller'=>'admin',
	  			'action'=>'add'
    		), 'default');
	    ?>">Dodaj użytkownika</a></li>
	</ul>
</div>

<hr class="bottom"/>

<div class="box text-right">
	<?= $pagination = $this->paginationControl($this->paginator, 'Sliding','_partial/pagination.phtml'); ?>
</div>

<hr class="bottom"/>

<table>
  <col span="2"/>
  <col class="even" span="3"/>
 <thead>
  <tr>
    <th>Nazwa</th>
    <th>Email</th>
    <th class="span-1">&nbsp;</th>
    <th class="span-1">&nbsp;</th>
    <th class="span-1">&nbsp;</th>
  </tr>
 </thead>
 <tbody>
  <?php if(empty($this->rowset)): ?>

   <tr>
    <td colspan="4"><p class="msg-notice bottom">Brak rekordów</p></td>
   </tr>

  <?php else: ?>

  <?php foreach ($this->rowset as $row): ?>
  <tr>
    <td><a href="<?php
    	print $this->url(
    		array(
	  			'module'=>'user',
	  			'controller'=>'admin',
	  			'action'=>'edit',
	  			'id' => $row->id
    		),'default'
    	);
    ?>"><?php print $row->username ?></a></td>
    <td><?php print $row->email ?></td>
    <td class="center">
    	<?php
    		if ($row->registered == 1) {
    			$registeredActionClass = 'true';
    			$registeredValue = 0;
    		} else {
    			$registeredActionClass = 'false';
    			$registeredValue = 1;
    		}
    	?>
    	<a
    		title="Zarejestrowany"
    		class="action ico small <?= $registeredActionClass ?>"
    		href="<?php
		    	print $this->url(
		    		array(
                                        'action'=>'modify',
                                        'id' => $row->id,
		    			'm_registered' => $registeredValue
		    		));
    	?>">zarejestrowany</a>
    </td>
    <td><a class="action edit small" href="<?php
    	print $this->url(
    		array(
	  			'module'=>'user',
	  			'controller'=>'admin',
	  			'action'=>'edit',
	  			'id' => $row->id
    		),'default'
    	);
    ?>">edytuj</a></td>
    <td class="center"><a
    	title="Usuń"
    	onclick="return confirm('Czy usunąć rekord?');"
    	class="action trash small ico" href="<?php
    	print $this->url(
    		array(
	  			'module'=>'user',
	  			'controller'=>'admin',
	  			'action'=>'delete',
	  			'id' => $row->id
    		),'default'
    	);
    ?>">usuń</a></td>
  </tr>
  <?php endforeach; ?>

  <?php endif; ?>
 </tbody>
</table>

<div class="box text-right">
	<?= $pagination = $this->paginationControl($this->paginator, 'Sliding','_partial/pagination.phtml'); ?>
</div>