<div class="span-24 last options-holder">
    <?php print $this->partial('_partial/common_head.phtml') ?>
</div>

<hr class="bottom"/>

<div class="span-2 options-holder">
	<h3>Akcje:</h3>
</div>

<div class="span-21 last options-holder">
	<ul class="options-list top-left">
		<li><a title="Dodaj wynik wyszukiwania" class="action small add" 
			   href="<?php print $this->url(array('action'=>'add'));?>">Dodaj wynik wyszukiwania</a></li>
	</ul>
</div>

<hr class="bottom"/>

<form action="" method="post">
<?php print $this->formSelect('action_type',null,null,array(
	'Wybierz akcje','update' => 'Aktualizuj', 'delete' => 'Usuń'
))?>
<?php print $this->formSubmit('default_action', 'Wykonaj akcje')?>
<?php print $this->grid->render($this, '_partial/newDataGrid.phtml');?>
</form>