<div class="span-24 last options-holder">
	<?= $this->partial('_partial/common_head.phtml', array('controller' => 'image')) ?>
</div>

<hr class="bottom"/>

<div class="span-2 options-holder">
	<h3>Akcje:</h3>
</div>

<div class="span-20 last options-holder">
	<ul class="options-list top-left">
		<li><a title="Dodaj grafikę" class="action add" href="<?php
	    	print $this->url(array(
	  			'controller'=>'image',
	  			'action'=>'add'
    		));
	    ?>">Dodaj grafikę</a></li>
	</ul>
	<ul class="options-list top-right">
	    <li><a title="" onclick="return confirm('Czy kontynuować?');" class="action small hot" href="<?php
	    	print $this->url(array(
	  			'controller'=>'image',
	  			'action'=>'convert'
    		),'default',false,false);
	    ?>">Konwertuj grafiki (!)</a></li>
	</ul>

</div>

<hr class="bottom"/>


<form method="get" action="<?php print $this->actionUrl ?><?php print $this->valuesQuery?>">
<?php
	print $this->dataGrid($this->grid, '_partial/newDataGrid.phtml');
?>
</form>