<div class="span-24 last options-holder">
	<?= $this->partial('_partial/common_head.phtml', array('controller' => 'district','action' => 'edit')) ?>
</div>

<hr class="bottom"/>

<div class="span-2 options-holder">
	<h3>Akcje:</h3>
</div>

<div class="span-20 last options-holder">
	<ul class="options-list top-left">
		<li><a title="Dodaj obszar" class="action add" href="<?php
	    	print $this->url(array(
	    		'controller' => 'district',
	  			'action'=>'add'
    		));
	    ?>">Dodaj obszar / dzielnicę</a></li>
	</ul>

</div>

<hr class="bottom"/>
<?php print $this->form ?>
<?php
	/* @var $headScript Zend_View_Helper_HeadScript */
	$headScript = $this->headScript();
	$headScript
		->offsetSetFile('6gmaps','js/backend/catalog/gmaps.js')
		->offsetSetFile('4jquery.ui.dialog','js/jquery/ui/1.7.2/minified/ui.dialog.min.js')
		->offsetSetFile('3jquery.ui.draggable','js/jquery/ui/1.7.2/minified/ui.draggable.min.js')
		->offsetSetFile('2jquery.ui','js/jquery/ui/1.7.2/minified/ui.core.min.js')
		->offsetSetFile('1jquery','http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js');

	$this->inlineScript()
		->appendFile('http://maps.google.com/maps?file=api&amp;v=2&amp;key='. G_MAP_KEY);

	$this->headLink()
		->appendStylesheet('js/jquery/ui/1.7.2/themes/ui-lightness/ui.all.css');
?>