<div class="span-24 last options-holder">
	<?= $this->partial('_partial/common_head.phtml', array('controller' => 'district')) ?>
</div>

<hr class="bottom"/>

<div class="span-2 options-holder">
	<h3>Akcje:</h3>
</div>

<div class="span-20 last options-holder">
	<ul class="options-list top-left">
		<li><a title="Dodaj obszar" class="action add" href="<?php
	    	print $this->url(array(
	    		'controller' => 'district',
	  			'action'=>'add'
    		));
	    ?>">Dodaj obszar / dzielnicę</a></li>
	</ul>

</div>

<hr class="bottom"/>

<table>
  <col span="2"/>
  <col class="odd"/>
  <col class="even" span="5"/>
 <thead>
  <tr>
    <th>Nazwa</th>
    <th class="span-7">Url</th>
    <th class="span-1">&nbsp;</th>
    <th class="span-1">&nbsp;</th>
    <th class="span-1">&nbsp;</th>
    <th class="span-1">&nbsp;</th>
  </tr>
 </thead>
 <tbody>
  <?php if(count($this->rowset) < 1): ?>

   <tr>
    <td colspan="6"><p class="msg-notice bottom">Brak rekordów</p></td>
   </tr>

  <?php else: ?>

  <?php foreach ($this->rowset as $row): ?>
  <tr>
   <td><?php print str_repeat('&nbsp;&nbsp;&nbsp;', $row->depth) ?><a href="<?php
    	print $this->url(array(
    		'controller' => 'district',
  			'action'=>'edit',
  			'id' => $row->id
    	));
    ?>"><?php print $row->name ?></a></td>
    <td class="small"><?php print $row->url ?></td>
    <td><a class="action add small" href="<?php
    	print $this->url(
    		array(
    			'controller' => 'district',
	  			'action'=>'add',
	  			'parent_id' => $row->id
    		));
    ?>">dodaj</a></td>
    <td><a class="action refresh small" href="<?php
    	print $this->url(
    		array(
    			'controller' => 'district',
	  			'action'=>'move',
	  			'id' => $row->id
    		));
    ?>">przenieś</a></td>
    <td><a class="action edit small" href="<?php
    	print $this->url(
    		array(
    			'controller' => 'district',
	  			'action'=>'edit',
	  			'id' => $row->id
    		));
    ?>">edytuj</a></td>
    <td class="center"><a
    	title="Usuń"
    	onclick="return confirm('Czy usunąć rekord?');"
    	class="action trash ico small" href="<?php
    	print $this->url(
    		array(
    			'controller' => 'district',
	  			'action'=>'delete',
	  			'id' => $row->id
    		));
    ?>">usuń</a></td>
  </tr>
  <?php endforeach; ?>

  <?php endif; ?>
 </tbody>
</table>