<div class="span-24 last options-holder">
	<?= $this->partial('_partial/common_head.phtml', array('controller' => 'district','action' => 'move')) ?>
</div>

<hr class="bottom"/>

<div class="span-2 options-holder">
	<h3>Akcje:</h3>
</div>

<div class="span-20 last options-holder">
	<ul class="options-list top-left">
		<li><a title="Dodaj obszar" class="action add" href="<?php
	    	print $this->url(array(
	    		'controller' => 'district',
	  			'action'=>'add'
    		));
	    ?>">Dodaj obszar / dzielnicę</a></li>
	</ul>

</div>

<hr class="bottom"/>

<?php if(!count($this->rowset) > 0): ?>
<p class="msg-notice">Brak kategorii</p>
<?php else: ?>
<form action="" method="post">
	<dl>
		<dt><label for="parentKey">Przenies od kategorii</label></dt>
		<dd>
			<select name="parent_key">
				<option value="root">&bull; Rekord główny!</option>
				<?php foreach ($this->rowset as $row): ?>
				<option value="<?= $row->id ?>"><?= str_repeat('&nbsp;&nbsp;&nbsp;', $row->depth) . $row->name ?></option>
				<?php endforeach; ?>
			</select>
		</dd>
		<dt></dt>
		<dd>
			<?= $this->formSubmit(null, 'Przenieś',array('class' => 'action refresh')) ?>
		</dd>
	</dl>
</form>
<?php endif; ?>