<?php print $this->doctype(); ?>
<html>
<head>
	<?php
		print $this->headBase();
    	print $this->headMeta();
    	print $this->headTitle();
    	print $this->headScript();
    	print $this->headLink();
    	print $this->headStyle();
    ?>
</head>
<body>
<div id="wrapper">
	<div class="adv head">
		<!--/* OpenX Javascript Tag v2.8.2 */-->
		
		<script type='text/javascript'><!--//<![CDATA[
		   var m3_u = (location.protocol=='https:'?'https://ads.eu1.pl/www/delivery/ajs.php':'http://ads.eu1.pl/www/delivery/ajs.php');
		   var m3_r = Math.floor(Math.random()*99999999999);
		   if (!document.MAX_used) document.MAX_used = ',';
		   document.write ("<scr"+"ipt type='text/javascript' src='"+m3_u);
		   document.write ("?zoneid=1");
		   document.write ('&amp;cb=' + m3_r);
		   if (document.MAX_used != ',') document.write ("&amp;exclude=" + document.MAX_used);
		   document.write (document.charset ? '&amp;charset='+document.charset : (document.characterSet ? '&amp;charset='+document.characterSet : ''));
		   document.write ("&amp;loc=" + escape(window.location));
		   if (document.referrer) document.write ("&amp;referer=" + escape(document.referrer));
		   if (document.context) document.write ("&context=" + escape(document.context));
		   if (document.mmm_fo) document.write ("&amp;mmm_fo=1");
		   document.write ("'><\/scr"+"ipt>");
		//]]>--></script><noscript><a href='http://ads.eu1.pl/www/delivery/ck.php?n=a4bb6caa&amp;cb=INSERT_RANDOM_NUMBER_HERE' target='_blank'><img src='http://ads.eu1.pl/www/delivery/avw.php?zoneid=1&amp;cb=INSERT_RANDOM_NUMBER_HERE&amp;n=a4bb6caa' border='0' alt='' /></a></noscript>
	</div>

	<div id="header">
		<?php print $this->partial('_partial/head.phtml')?>

		<ul id="subnav" class="usluga">
			<li class="first"><h1><?php print $this->escape(@$this->row['name']) ?></h1></li>
		</ul>
	</div>

	<div id="content">
		<!-- Kolumna 1 - lewa -->
		<div class="col c1 wide">
			<?php print $this->layout()->content ?>
		</div>
		
		<!-- Kolumna 2 - prawa -->
		<div class="col c3">
			<div class="adv sitebar">		
				<!--/* OpenX Javascript Tag v2.8.2 */-->
	
				<script type='text/javascript'><!--//<![CDATA[
				   var m3_u = (location.protocol=='https:'?'https://ads.eu1.pl/www/delivery/ajs.php':'http://ads.eu1.pl/www/delivery/ajs.php');
				   var m3_r = Math.floor(Math.random()*99999999999);
				   if (!document.MAX_used) document.MAX_used = ',';
				   document.write ("<scr"+"ipt type='text/javascript' src='"+m3_u);
				   document.write ("?zoneid=3");
				   document.write ('&amp;cb=' + m3_r);
				   if (document.MAX_used != ',') document.write ("&amp;exclude=" + document.MAX_used);
				   document.write (document.charset ? '&amp;charset='+document.charset : (document.characterSet ? '&amp;charset='+document.characterSet : ''));
				   document.write ("&amp;loc=" + escape(window.location));
				   if (document.referrer) document.write ("&amp;referer=" + escape(document.referrer));
				   if (document.context) document.write ("&context=" + escape(document.context));
				   if (document.mmm_fo) document.write ("&amp;mmm_fo=1");
				   document.write ("'><\/scr"+"ipt>");
				//]]>--></script><noscript><a href='http://ads.eu1.pl/www/delivery/ck.php?n=a69df72d&amp;cb=INSERT_RANDOM_NUMBER_HERE' target='_blank'><img src='http://ads.eu1.pl/www/delivery/avw.php?zoneid=3&amp;cb=INSERT_RANDOM_NUMBER_HERE&amp;n=a69df72d' border='0' alt='' /></a></noscript>
			</div>
		
			<?php print $this->catalogPremium()
							 ->setRandom(true)
							 ->setRowCount(6)
							 ->render('_partial/catalogPremium.phtml')?>
							 
			<div class="adv sitebar asvbottom">
				<!--/* OpenX Javascript Tag v2.8.2 */-->

				<script type='text/javascript'><!--//<![CDATA[
				   var m3_u = (location.protocol=='https:'?'https://ads.eu1.pl/www/delivery/ajs.php':'http://ads.eu1.pl/www/delivery/ajs.php');
				   var m3_r = Math.floor(Math.random()*99999999999);
				   if (!document.MAX_used) document.MAX_used = ',';
				   document.write ("<scr"+"ipt type='text/javascript' src='"+m3_u);
				   document.write ("?zoneid=13");
				   document.write ('&amp;cb=' + m3_r);
				   if (document.MAX_used != ',') document.write ("&amp;exclude=" + document.MAX_used);
				   document.write (document.charset ? '&amp;charset='+document.charset : (document.characterSet ? '&amp;charset='+document.characterSet : ''));
				   document.write ("&amp;loc=" + escape(window.location));
				   if (document.referrer) document.write ("&amp;referer=" + escape(document.referrer));
				   if (document.context) document.write ("&context=" + escape(document.context));
				   if (document.mmm_fo) document.write ("&amp;mmm_fo=1");
				   document.write ("'><\/scr"+"ipt>");
				//]]>--></script><noscript><a href='http://ads.eu1.pl/www/delivery/ck.php?n=a44ca66b&amp;cb=INSERT_RANDOM_NUMBER_HERE' target='_blank'><img src='http://ads.eu1.pl/www/delivery/avw.php?zoneid=13&amp;cb=INSERT_RANDOM_NUMBER_HERE&amp;n=a44ca66b' border='0' alt='' /></a></noscript>
								
			</div>
		</div>
	</div>

	<div class="doubleLine"></div>
	<div id="footer">
		<?php print $this->partial('_partial/foot.phtml')?>
		<?php print $this->partial('_partial/footSub.phtml')?>
	</div>

</div>
<?php print htmlspecialchars_decode($this->inlineScript())?>
</body>
</html>
