<?php $url = $this->getHelper('url')?>
<?php foreach ((array) $this->rowset as $row):?>
<div class="row <?php print $this->cycle(array('odd','even'))?>">
	<h4><a href="<?php print $url->url(array('id' => $row['id']), 'catalog-show'); ?>"><?php print $this->escape($row['name'])?></a></h4>
	<a class="more" href="<?php print $url->url(array('id' => $row['id']), 'catalog-show'); ?>">szczegóły &raquo;</a>
</div>
<?php endforeach;?>

<div class="end"><a href="<?php print $this->url(array(),'catalog-category',true)?>">zobacz więcej &raquo;</a></div>