<div class="span-24 last options-holder">
	<?= $this->partial('_partial/common_head.phtml') ?>
</div>

<hr class="bottom"/>

<div class="span-2 options-holder">
	<h3>Akcje:</h3>
</div>

<div class="span-20 last options-holder">
	<ul class="options-list top-left">
		<li><a title="Dodaj wpis" class="action refresh" href="<?php
	    	print $this->url(array(
	    		'module' => 'agregator',
	  			'controller'=>'agregator',
	  			'action'=>'agregateall'
    		),'default',false,false);
	    ?>">Sprawdż czy sa nowe wpisy</a> <span class="small">jak są to dodaj je do bazy danych</span></li>
	</ul>
</div>

<hr class="bottom"/>

<form action="" method="post">
<?php
	$renderer = $this->grid->getRenderer();
	$renderer->setPartial('_partial/dataGrid.phtml');
	print $this->grid->render();
?>
</form>