<?php switch ($this->catalog_promo_type_id):?>
<?php case '3':?>
<div class="offerBox premium">
	<?php if(strlen(@$this->image) > 2):?>
	<a href="<?php print $this->getHelper('Url')->url(array('id' => $this->id), 'catalog-show'); ?>">
		<img src="/upload/catalog/image/logo/<?php print $this->escape($this->image)?>" alt="Logo: <?php print $this->escape($this->name)?>" class="offerLogo" /></a>
	<?php endif;?>

	<p class="breadcrumb"><a href="<?php print $this->getHelper('Url')->url(array('id' => $this->id), 'catalog-show'); ?>">zobacz więcej &raquo; </a></p>
	<h4><a href="<?php print $this->getHelper('Url')->url(array('id' => $this->id), 'catalog-show'); ?>"><?php print $this->escape($this->name)?></a></h4>
	<p class="address">
		<a href="<?php print $this->url(array('url' => $this->district_url),'catalog-category',true)?>"><?php print $this->district?></a>, 
		<a href="/szukaj?q=<?php print $this->escape($this->adress)?>"><?php print $this->escape($this->adress)?></a></p>
	
	<ul>
		<?php if(strlen(@$this->option1) > 2):?>
		<li><a href="<?php print $this->getHelper('Url')->url(array('id' => $this->id), 'catalog-show'); ?>"><?php print $this->option1?></a></li>
		<?php endif;?>
		<?php if(strlen(@$this->option2) > 2):?>
		<li><a href="<?php print $this->getHelper('Url')->url(array('id' => $this->id), 'catalog-show'); ?>"><?php print $this->option2?></a></li>
		<?php endif;?>
		<?php if(strlen(@$this->option3) > 2):?>
		<li><a href="<?php print $this->getHelper('Url')->url(array('id' => $this->id), 'catalog-show'); ?>"><?php print $this->option3?></a></li>
		<?php endif;?>
	</ul>
	<img class="mapRank" src="css/<?php print CATALOG_TYPE?>/img/gmap/marker-premium.png" alt="" />
</div>
<?php break;?>

<?php case '2':?>
<div class="offerBox medium">
	<?php if(strlen(@$this->image) > 2):?>
	<a href="<?php print $this->getHelper('Url')->url(array('id' => $this->id), 'catalog-show'); ?>">
		<img src="/upload/catalog/image/logo/<?php print $this->escape($this->image)?>" alt="Logo: <?php print $this->escape($this->name)?>" class="offerLogo" /></a>
	<?php endif;?>

	<p class="breadcrumb"><a href="<?php print $this->getHelper('Url')->url(array('id' => $this->id), 'catalog-show'); ?>">zobacz więcej &raquo; </a></p>
	<h4><a href="<?php print $this->getHelper('Url')->url(array('id' => $this->id), 'catalog-show'); ?>"><?php print $this->escape($this->name)?></a></h4>
	<p class="address">
		<a href="<?php print $this->url(array('url' => $this->district_url),'catalog-category',true)?>"><?php print $this->district?></a>, 
		<a href="/szukaj?q=<?php print $this->escape($this->adress)?>"><?php print $this->escape($this->adress)?></a></p>
	<img class="mapRank" src="css/<?php print CATALOG_TYPE?>/img/gmap/marker-medium.png" alt="" />
</div>
<?php break;?>

<?php case '1':?>
<div class="offerBox standard">
	<?php if(strlen(@$this->image) > 2):?>
	<a href="<?php print $this->getHelper('Url')->url(array('id' => $this->id), 'catalog-show'); ?>">
		<img src="/upload/catalog/image/logo/<?php print $this->escape($this->image)?>" alt="Logo: <?php print $this->escape($this->name)?>" class="offerLogo" /></a>
	<?php endif;?>

	<p class="breadcrumb"><a href="<?php print $this->getHelper('Url')->url(array('id' => $this->id), 'catalog-show'); ?>">zobacz więcej &raquo; </a></p>
	<h4><a href="<?php print $this->getHelper('Url')->url(array('id' => $this->id), 'catalog-show'); ?>"><?php print $this->escape($this->name)?></a></h4>
	<p class="address">
		<a href="<?php print $this->url(array('url' => $this->district_url),'catalog-category',true)?>"><?php print $this->district?></a>,
		<a href="/szukaj?q=<?php print $this->escape($this->adress)?>"><?php print $this->escape($this->adress)?></a></p>
	<img class="mapRank" src="css/<?php print CATALOG_TYPE?>/img/gmap/marker-standard.png" alt="" />
</div>
<?php break;?>
<?php default:?>
<div class="offerBox standard">
	<p class="breadcrumb"><a href="<?php print $this->getHelper('Url')->url(array('id' => $this->id), 'catalog-show'); ?>">zobacz więcej &raquo; </a></p>
	<h4><a href="<?php print $this->getHelper('Url')->url(array('id' => $this->id), 'catalog-show'); ?>"><?php print $this->escape($this->name)?></a></h4>
	<p class="address">
		<a href="<?php print $this->url(array('url' => $this->district_url),'catalog-category',true)?>"><?php print $this->district?></a>,
		<a href="/szukaj?q=<?php print $this->escape($this->adress)?>"><?php print $this->escape($this->adress)?></a></p>
	<img class="mapRank" src="css/<?php print CATALOG_TYPE?>/img/gmap/marker-default.png" alt="" />
</div>
<?php break;?>
<?php endswitch;?>