<ul>
<?php foreach ((array) $this->rowset as $row):?>
	<?php if (strlen(@$row['alias']) > 1):?>
	<li>
		<?php if ($row['subdomain']):?>
			<a href="<?php print $this->url(array('alias' => $row['alias']), 'catalogServiceWww')?>"><?php print $this->escape($row['name'])?></a>
		<?php else:?>
			<a href="<?php print $this->url(array('id' => $row['alias']), 'catalog-service')?>"><?php print $this->escape($row['name'])?></a>
		<?php endif;?>
	</li>
	<?php else:?>
	<li><a href="<?php print $this->url(array('id' => $row['id']), 'catalog-service')?>"><?php print $this->escape($row['name'])?></a></li>
	<?php endif;?>
<?php endforeach;?>
</ul>