<p class="copyright"><a href="<?php print $this->url(array(),'agregator-index',true) ?>">Jak zadbać o swojego zwierzaka!</a></p>

<ul>
	<li>&#9642; <a href="<?php print $this->url(array(),'catalog-main',true) ?>">Strona Główna</a></li>
	<li>&#9642; <a href="<?php print $this->url(array('url' => 'informacje-dla-weterynarzy'),'page-page',true) ?>">Informacje dla weterynarzy</a></li>
	<li>&#9642; <a href="<?php print $this->url(array('url' => 'reklama'),'page-page',true) ?>">Reklama</a></li>
	<li>&#9642; <a href="<?php print $this->url(array('url' => 'polityka-prywatnosci'),'page-page',true) ?>">Polityka Prywatności</a></li>
	<li>&#9642; <a href="<?php print $this->url(array('url' => 'kontakt'),'page-page',true) ?>">Kontakt</a></li>
</ul>

<ins class="clear space-small"></ins>

<ul id="promofoot">
  <li>
  	<a href="http://prawnicy.krakow.pl/" title="Notariusz w Krakowie"><img src="http://prawnicy.krakow.pl/images/prawnicy/logo_32x32.png" width="24" height="24" alt="notariusz kraków" /></a>
  	<a href="http://prawnicy.krakow.pl/" title="Prawnik w Krakowie">Prawnik Kraków</a>
  </li>
  <li>
  	<a href="http://stomatolodzy.krakow.pl/" title="Kliknij i zobacz najlepszych stomatologów w Krakowie!"><img src="http://stomatolodzy.krakow.pl/images/stomatolodzy/logo_32x32.png" width="24" height="24" alt="dentysta kraków" /></a>
  	<a href="http://stomatolodzy.krakow.pl/" title="Kliknij i zobacz najlepszych stomatologów w Krakowie">Stomatolog Kraków</a>
  </li>
  <li>
  	<a href="http://lekarze.krakow.pl/" title="Zdrowie w Krakowie"><img src="http://lekarze.krakow.pl/images/lekarze/logo_32x32.png" width="24" height="24" alt="lekarz kraków" /></a>
  	<a href="http://lekarze.krakow.pl/" title="Lekarze w Krakowie">Lekarz Kraków</a>
  </li>
  <li>
  	<a href="http://fryzjerzy.krakow.pl/" title="Dobry salon fryzjerski Kraków!"><img src="http://fryzjerzy.krakow.pl/images/fryzjerzy/logo_32x32.png" width="24" height="24" alt="salon fryzjerski kraków" /></a>
  	<a href="http://fryzjerzy.krakow.pl/" title="Dobry fryzjer w Krakowie">Fryzjer Kraków</a>
  </li>
</ul>


<p class="small">Mapy udostępnione przez <a href="http://google.pl">Google.pl</a></p>

<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
try {
var pageTracker = _gat._getTracker("UA-8366844-1");
pageTracker._trackPageview();
} catch(err) {}</script>
