<?php 

	/**
	 * Wieksze od jeden dlatego że pierwszą grafiką jest logo! 
	 * a nie chcemy żeby się wyświetlało ponownie
	 */
	if(count($this->imagesRowset) > 1):
?>

<p class="msg-notice">Fotografie nie zostały dodane!</p>

<?php else: ?>

<ul id="jcarousel" class="jcarousel-skin-tango">
	<?php foreach ($this->imagesRowset as $image):?>
	<li>
		<a href="<?php print $this->url(array('type' => "thumb3", 'file' => $image->image),'catalogImage');?>" rel="nofollow lightbox">
		<img src="<?php print $this->url(array('type' => "thumb1", 'file' => $image->image),'catalogImage');?>" /></a></li>
	<?php endforeach;?>
</ul>

<?php endif;?>