<?php print '<?xml version="1.0" encoding="UTF-8"?>'?>
<?php $baseUrl = $this->baseUrl()?>
<kml xmlns="http://www.opengis.net/kml/2.2">
<Document>
<Style id="wetIconDefault">
	<IconStyle>
		<color>ff00ff00</color>
		<colorMode>random</colorMode>
		<scale>1</scale>
		<Icon>
			<href><?php print $baseUrl?>/images/<?php print CATALOG_TYPE ?>/gmap/default</href>
		</Icon>
	</IconStyle>
</Style>
<Style id="wetIconStandard">
	<IconStyle>
		<color>ff00ff00</color>
		<colorMode>random</colorMode>
		<scale>1</scale>
		<Icon>
			<href><?php print $baseUrl?>/images/<?php print CATALOG_TYPE ?>/gmap/standard.png</href>
		</Icon>
	</IconStyle>
</Style>
<Style id="wetIconMedium">
	<IconStyle>
		<color>ff00ff00</color>
		<colorMode>random</colorMode>
		<scale>1</scale>
		<Icon>
			<href><?php print $baseUrl?>/images/<?php print CATALOG_TYPE ?>/gmap/medium.png</href>
		</Icon>
	</IconStyle>
</Style>
<Style id="wetIconPremium">
		<color>ff00ff00</color>
		<colorMode>random</colorMode>
		<scale>1</scale>
		<Icon>
			<href><?php print $baseUrl?>/images/<?php print CATALOG_TYPE ?>/gmap/premium.png</href>
		</Icon>
	</IconStyle>
</Style>
<?php foreach ($this->rowset as $row):?>
<Placemark>
	<name><?php print $row['name']?></name>
	<visibility>1</visibility>
	<open>1</open>
	<address><?php print $this->escape($row['adress'])?></address>
	<description>
			&lt;a href="<?php print $baseUrl?>" title="<?php print CATALOG_NAME ?>"&gt;
				&lt;img src="<?php print $baseUrl?>/images/<?php print CATALOG_TYPE ?>/logo-small.png"/&gt;
			&lt;/a&gt;

			<?php if (strlen($row['image'])):?>
			&lt;img align="right" src="<?php print $baseUrl?>/upload/catalog/image/logo/<?php print $row['image']?>" alt="<?php print $row['name']?>" /&gt;
			<?php endif;?>

			&lt;h3&gt;<?php print $row['name']?>&lt;/h3&gt;
			&lt;dl&gt;
				&lt;dt&gt;Adress:&lt;/dt&gt;
				&lt;dl&gt;<?php print $this->escape($row['adress'])?>&lt;/dl&gt;
				
				&lt;dt&gt;&lt;a style="color:green" href="<?php print $baseUrl . $this->url(array('id' => $row['id']), 'catalog-show')?>"&gt;<?php print $baseUrl . $this->url(array('id' => $row['id']), 'catalog-show')?>&lt;/a&gt;&lt;/dt&gt;

				&lt;dt&gt;Telefon:&lt;/dt&gt;
				&lt;dl&gt;&lt;a href="<?php print $this->url(array('id' => $row['id']), 'catalog-show')?>"&gt;pokaż numer telefonu&lt;/a&gt;&lt;/dl&gt;

				&lt;dt&gt;Godziny pracy:&lt;/dt&gt;
				&lt;dl&gt;&lt;a href="<?php print $this->url(array('id' => $row['id']), 'catalog-show')?>"&gt;pokaż gdziny pracy&lt;/a&gt;&lt;/dl&gt;

				&lt;dt&gt;Usługi:&lt;/dt&gt;
				&lt;dl&gt;&lt;a href="<?php print $this->url(array('id' => $row['id']), 'catalog-show')?>"&gt;pokaż usługi&lt;/a&gt;&lt;/dl&gt;

				&lt;dt&gt;Personel:&lt;/dt&gt;
				&lt;dl&gt;&lt;a href="<?php print $this->url(array('id' => $row['id']), 'catalog-show')?>"&gt;pokaż personel&lt;/a&gt;&lt;/dl&gt;
			&lt;/dl&gt;
	</description>
	<styleUrl>#<?php
		switch ($row['catalog_promo_type_id']) {
			case '3': print 'wetIconPremium'; break;
			case '2': print 'wetIconMedium'; break;
			case '1': print 'wetIconStandard'; break;
			default:  print 'wetIconDefault'; break;
		}?></styleUrl>
	<Point>
		<coordinates><?php print $row['lng']?>,<?php print $row['lat']?></coordinates>
	</Point>
</Placemark>
<?php endforeach;?>
</Document>
</kml>