<ul id="promofoot">
  <li>
  	<a href="http://prawnicy.krakow.pl/" title="Szukasz Prawnika? Notariusza? Radce Prawnego?.. Kliknij!"><img src="http://prawnicy.krakow.pl/images/prawnicy/logo_32x32.png" width="24" height="24" alt="radca prawny kraków" /></a>
  	<a href="http://prawnicy.krakow.pl/" title="Szukasz Prawnika? Notariusza? Radce Prawnego?.. Kliknij!">Notariusz Kraków</a>
  </li>
  <li>
  	<a href="http://weterynarze.krakow.pl/" title="Weterynarze w Krakowie"><img src="http://weterynarze.krakow.pl/images/weterynarze/logo_32x32.png" width="24" height="24" alt="weterynarze Kraków" /></a>
  	<a href="http://weterynarze.krakow.pl/" title="Weterynarz w Krakowie">Weterynarz Kraków</a>
  </li>
  <li>
  	<a href="http://lekarze.krakow.pl/" title="Zdrowie w Krakowie"><img src="http://lekarze.krakow.pl/images/lekarze/logo_32x32.png" width="24" height="24" alt="lekarz kraków" /></a>
  	<a href="http://lekarze.krakow.pl/" title="Lekarze w Krakowie">Lekarz Kraków</a>
  </li>
  <li>
  	<a href="http://stomatolodzy.krakow.pl/" title="Kliknij i zobacz najlepszych stomatologów w Krakowie!"><img src="http://stomatolodzy.krakow.pl/images/stomatolodzy/logo_32x32.png" width="24" height="24" alt="dentysta kraków" /></a>
  	<a href="http://stomatolodzy.krakow.pl/" title="Kliknij i zobacz najlepszych stomatologów w Krakowie">Stomatolog Kraków</a>
  </li>
</ul>

<p class="small">Mapy udostępnione przez <a href="http://google.pl">Google.pl</a></p>

<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
try {
var pageTracker = _gat._getTracker("UA-15672157-1");
pageTracker._trackPageview();
} catch(err) {}</script>
