<?php 
	if (!count($this->rowset))
	{
		return;
	}

	$url = $this->getHelper('Url');
?>
<ul id="people-container">
<?php 
	foreach ((array) $this->rowset as $row):
		$urlCatalogShow = $url->url(array('id' => $this->id), 'catalog-show');
?>
<li class="first premium">
	<span class="nr"><strong><?php print $row['id']?></strong></span>
	<a href="<?php print $urlCatalogShow ?>">
	<span class="crumbs">Spis ofert   <strong>Prawnik Kraków</strong></span></a>
	<a href="<?php print $url->url(array('id' => $row['id']), 'catalog-show'); ?>"><span class="name"><?php print $this->escape($row['name'])?></span></a>
	<span class="address">
		<a href="<?php print $url->url(array('url' => $row['district_url']),'catalog-category',true)?>"><?php print $row['district'];?></a>
		<a href="/szukaj?q=<?php print $this->escape($row['adress'])?>"><?php print $this->escape($row['adress'])?></a>
	</span>

	<?php if(strlen(@$row['image']) > 2):?>
	<a href="<?php print $urlCatalogShow ?>">
		<img class="logo" src="/upload/catalog/image/logo/<?php print $this->escape($row['image'])?>" alt="<?php print $this->escape($row['name'])?>" /></a>
	<?php endif;?>
	
	<ul class="sub">
		<?php if(strlen(@$row['option1']) > 2):?>
		<li class="first"><a href="<?php print $url->url(array('id' => $row['id']), 'catalog-show'); ?>"><?php print $row['option1']?></a></li>
		<?php endif;?>
		<?php if(strlen(@$row['option2']) > 2):?>
		<li><a href="<?php print $url->url(array('id' => $row['id']), 'catalog-show'); ?>"><?php print $row['option2']?></a></li>
		<?php endif;?>
		<?php if(strlen(@$row['option3']) > 2):?>
		<li class="last"><a href="<?php print $url->url(array('id' => $row['id']), 'catalog-show'); ?>"><?php print $row['option3']?></a></li>
		<?php endif;?>
	</ul>
</li>
<?php endforeach;?>
</ul>