<ins class="clear space-small"></ins>

<div class="dd">
	<div id="foot-service" class="dd50">
		<span>Usługi:</span>
		<?php print $this->catalogService()->render('_partial/catalogServiceFoot.phtml') ?>
	</div>
	<div id="foot-options" class="dd50">
		<span>Gabinet zapewnia:</span>
		<?php print $this->catalogOptions()->render('_partial/catalogOptionsFoot.phtml') ?>
	</div>
	<div id="foot-type" class="dd50">
		<span>Rodzaj gabinetu:</span>
		<?php print $this->catalogType()->render('_partial/catalogTypeFoot.phtml') ?>
	</div>
</div>

<ins class="clear space-small"></ins>

<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
try {
var pageTracker = _gat._getTracker("UA-7556328-1");
pageTracker._trackPageview();
} catch(err) {}</script>