<div id="upper">
	<a class="fryzjerzykrakow" href="http://fryzjerzy.krakow.pl"><img src="css/newfryzjerzy/files/fryzjerzykrakow.png" width="157" height="22" alt="Fryzjer Kraków" /><strong>Fryzjer Kraków</strong></a>
	<ul class="upper-menu">
		<li class="home"><a href="http://fryzjerzy.krakow.pl" rel="nofallow">strona główna</a></li>
		<li class="contact"><a href="http://fryzjerzy.krakow.pl/pl/strona/kontakt">kontakt</a></li>
	</ul>
</div>
<div id="navigation">
	<ul class="menu left">
		<li class="first home"><a href="<?php print $this->url(array(),'catalog-main',true) ?>">
			<span><strong>Strona główna</strong></span></a></li>
		<li class="list"><a href="<?php print $this->url(array(),'catalog-category',true) ?>">
			<span><strong>Spis</strong></span></a></li>
		<li class="search"><a href="<?php print $this->url(array(),'catalog-search',true) ?>">
			<span><strong>Wyszukiwarka</strong></span></a></li>
		<li class="last info"><a href="<?php print $this->url(array('url' => 'informacje-dla-fryzjerow'),'page-page',true) ?>">
			<span><strong>Informacje dla fryzjerów</strong></span></a></li>
	</ul>
	<ul class="menu right">
        <li class="last gallery"><a href="<?php print $this->url(array('alias' => 'galeria'),'catalogWww-index',true) ?>">
			<span><strong>Galeria fryzur</strong></span></a></li>       
		<li class="last cosme"><a href="<?php print $this->url(array('alias' => 'instytucje'),'catalogWww-index',true) ?>">
			<span><strong>Profesjonalne kosmetyki</strong></span></a></li>
	</ul>
</div>

<?php if (count($messages = $this->FlashMessages())):?>
<ul id="flashMessages">
	<?php foreach ($messages as $message):?>
	<li><?php print $this->escape($message)?></li>
	<?php endforeach;?>
</ul>
<?php endif;?>