<div class="span-24 last options-holder">
    <?php print $this->partial('_partial/common_head.phtml') ?>
</div>

<hr class="bottom"/>

<form action="" method="post">
<?php print $this->formSelect('action_type',null,null,array(
	'Wybierz akcje','update' => 'Aktualizuj', 'delete' => 'Usuń'
))?>
<?php print $this->formSubmit('default_action', 'Wykonaj akcje')?>
<?php print $this->grid->render($this, '_partial/newDataGrid.phtml');?>
</form>