<div class="span-24 last options-holder">
    <?php print $this->partial('_partial/common_head.phtml') ?>
</div>

<hr class="bottom"/>

<form action="" method="post">
<?php print $this->formSelect('action_type',null,null,array(
	'Wybierz akcje','update' => 'Aktualizuj', 'delete' => 'Usuń'
))?>
<?php print $this->formSubmit('default_action', 'Wykonaj akcje')?>
<?php
	$renderer = $this->grid->getRenderer();
	$renderer->setPartial('_partial/newDataGrid.phtml');
	print $this->grid->render($renderer);
?>
</form>