<ul>
	<!-- 
	<li><a class="action ico big home" href="<?php print $this->url(array('module' => 'admin', 'controller' => 'index', 'action' => 'index'),'default',true); ?>">Strona główna</a></li>
	 -->
	<li><a class="action ico big content" href="<?php print $this->url(array('module' => 'page', 'controller' => 'admin', 'action' => 'index'),'default',true); ?>">Treść</a></li>
	
	<li><br/><hr/></li>
	
	<li><a class="action ico big folder" href="<?php print $this->url(array('module' => 'catalog', 'controller' => 'admin', 'action' => 'index'),'default',true); ?>">Katalog</a></li>
	
	<li><br/><hr/></li>				
        <li><a class="action ico big stats" href="<?php print $this->url(array('module' => 'advertising', 'controller' => 'admin', 'action' => 'index'),'default',true); ?>">Reklama</a></li>
	<li><br/><hr/></li>
	
	<li><a class="action ico big user" href="<?php print $this->url(array('module' => 'user', 'controller' => 'admin', 'action' => 'index'),'default',true); ?>">Użytkowik</a></li>
	<li><a class="action ico big settings" href="<?php print $this->url(array('module' => 'system', 'controller' => 'admin', 'action' => 'index'),'default',true); ?>">System</a></li>
</ul>