<?php print $this->doctype(); ?>
<html>
<head>
	<?php
		print $this->headBase();
    	print $this->headMeta();
    	print $this->headTitle();
    	print $this->headScript();
    	print $this->headLink();
    	print $this->headStyle();
    ?>
</head>
<body>
<div class="container">
<?php print $this->partial('_partial/user_panel.phtml') ?>

<div id="head" class="span-24 last">
	<?php print $this->partial('_partial/head.phtml') ?>
</div>

<div class="span-16">
	<div id="loader">Wczytuję..</div>
	<div id="content">
		<?php print $this->partial('_partial/messages.phtml',array('messages' => $this->messages)) ?>
		
		<?php print $this->layout()->content ?>
	</div><!-- content -->
</div>

<div class="span-8 last">
	<div id="gmap-container" class="border">
		<div class="wrapper">
			<h3 class="shadow">Lokalizacja <span>Lokalizacja</span></h3>
			<p id="gmap-js" class="msg-info">Nie można wyświetlić mapy. Twoja przeglądarka nie ma włączonej obsługi języka JavaScript!</p>
			<p id="gmap-compatible" class="msg-info none">Nie można wyświetlić mapy. Przeglądarka nie jest kompatybilna z Google Maps!</p>
			<div id="gmap"></div>
		</div>
	</div>

    <div id="image-list">
        <?php print $this->partial('index/show/image-list.phtml', $this)?>
    </div>
</div>

<div class="span-24 last clear">
	<?php  print $this->partial('_partial/foot.phtml') ?>
</div>
</div>
</body>
</html>
