<h2>Znalazłeś jakiś błąd lub masz jakieś sugestie co do funkcjonalności serwisu?</h2>

<div class="span-7">
	<p>Podziel się z nami swoją opinią. Stwórzmy razem portal wygodny dla nas wszystkich!</p>
	<p class="bottom">Przekaż nam swoje uwagi na 3 sposoby:</p>
	<ul style="list-style: decimal">
		<li>Wypełnij formularz zgłoszenia obok</li>
		<li>Wyślij e-maila na adres <a href="mailto:blad@stomatolodzy.krakow.pl">blad@stomatolodzy.krakow.pl</a></li>
		<li>Zadzwoń lub wyślij fax na nr (012) 429 45 86</li>
	</ul>
	<p><strong><big>Każda opinia jest dla nas ważna!</big></strong></p>
</div>
<div class="span-11 last">
	<?php print $this->form?>
</div>