<div class="span-18 options-holder">
    <?= $this->partial('_partial/common_head.phtml', array('controller' => 'type','action' => 'edit')) ?>
</div>
<div class="span-4 last options-holder">
    <ul class="options-list top-right">
        <li><a title="Dodaj type" class="action add" href="<?php print $this->url(array(
                   'module'=>'advertising',
                   'controller'=>'type',
                   'action'=>'add'),'default',false,false);?>">Dodaj typ</a></li>
    </ul>
</div>

<hr class="bottom"/>
<?php print $this->form ?>