<div class="span-24 last options-holder">
	<?= $this->partial('_partial/common_head.phtml', array('controller' => 'site','action' => 'edit')) ?>
</div>

<hr class="bottom"/>

<div class="span-2 options-holder">
	<h3>Akcje:</h3>
</div>

<div class="span-20 last options-holder">
	<ul class="options-list top-left">
		 <li><a title="Dodaj stronę" class="action add" href="<?php print $this->url(array(
               'module' => 'catalog',
               'controller'=>'site',
               'action'=>'add'
           ),'default',false,false); ?>">Dodaj stronę (wizytówki)</a></li>
	</ul>
</div>

<hr class="bottom"/>
<?php print $this->form ?>