<div class="span-24 last options-holder">
	<?= $this->partial('_partial/common_head.phtml', array('controller' => 'optionshas','action' => 'add')) ?>
</div>

<hr class="bottom"/>

<div class="span-2 options-holder">
	<h3>Akcje:</h3>
</div>

<div class="span-20 last options-holder">
	<ul class="options-list top-left">
		<li><a title="Dodaj type" class="action add" href="<?php
	    	print $this->url(array(
	    		'module' => 'catalog',
	  			'controller'=>'optionshas',
	  			'action'=>'add'
    		),'default',false,false);
	    ?>">Dodaj pojedyńczą opcje (gabinet oferuje)</a></li>
	    <li><a title="Dodaj type" class="action add" href="<?php
	    	print $this->url(array(
	    		'module' => 'catalog',
	  			'controller'=>'optionshas',
	  			'action'=>'addmulti'
    		),'default',false,false);
	    ?>">Dodaj kilka opcji (gabinet oferuje)</a></li>
	</ul>
</div>

<hr class="bottom"/>
<?php print $this->form ?>