<div class="span-24 last options-holder">
	<?= $this->partial('_partial/common_head.phtml', array('controller' => 'service','action' => 'add')) ?>
</div>

<hr class="bottom"/>

<div class="span-2 options-holder">
	<h3>Akcje:</h3>
</div>

<div class="span-20 last options-holder">
	<ul class="options-list top-left">
		<li><a title="Dodaj usługę" class="action add" href="<?php
	    	print $this->url(array(
	    		'module' => 'catalog',
	  			'controller'=>'service',
	  			'action'=>'add'
    		),'default',false,false);
	    ?>">Dodaj rodzaj usługi</a></li>
	</ul>

</div>

<hr class="bottom"/>
<div class="msg-info">
	<ul class="bottom">
		<li>Rodzaje usług muszą być jak najdokładniej opisane!</li>
		<li>Opcje nie powinny się powtarzać!</li>
		<li>Alias powinien być krótki gdyż odpowiada za adres strony (subdomene)!</li>
	</ul>
</div>

<hr />

<?php print $this->form ?>