<?php print $this->doctype(); ?>
<html>
<head>
	<?php
		print $this->headBase();
    	print $this->headMeta();
    	print $this->headTitle();
    	print $this->headScript();
    	print $this->headLink();
    	print $this->headStyle();
    ?>
</head>
<body>
<div id="wrapper" class="home">
   	<?php print $this->partial('_partial/head.phtml')?>
   	
	<div id="container">
		<div class="column c66 darkpink">
			<div class="inner">
				<?php print $this->layout()->content ?>
			</div>
		</div>
		<div class="column c33 sidebar"></div>
	</div>
        
	<div id="footer">
        <?php print $this->partial('_partial/foot.phtml')?>
	</div>

	<div id="bottom">
        <?php print $this->partial('_partial/bottom.phtml')?>
	</div>
   </div>
</body>
<?php print $this->inlineScript()?>
</html>