<?php print $this->doctype(Zend_View_Helper_Doctype::XHTML1_TRANSITIONAL); ?>
<html>
<head>
   <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
   <meta name="verify-v1" content="iSwhnwLZAqfcrsAE6CVSldZ30jpkw4E7xVeqgldbL3w=" />
   <meta name="msvalidate.01" content="CCC412BFA9383569FACFD4E1D04FE5BA" />
    <?php
    	$baseUrl = KontorX_View_Helper_BaseUrl::baseUrl();
	?>
	<base href="<?php print $baseUrl?>" />
	<link rel="shortcut icon" href="favicon.png" type="image/png">
	<?php
    	print $this->headMeta();
    	print $this->headTitle();
    	// &amp; -> & becouse gmaps crash!
    	print htmlspecialchars_decode($this->headScript());
    	print $this->headLink();
    	print $this->headStyle();
    ?>
</head>
<body>
<div class="container">
<?php print $this->partial('_partial/user_panel.phtml') ?>

<div id="head" class="span-24 last">
	<?php print $this->partial('_partial/head.phtml') ?>
</div>

<div class="span-24 last">
<?php print $this->partial('_partial/messages.phtml',array('messages' => $this->messages)) ?>
</div>

<div class="span-18">
	<div class="border">
		<div id="manage_navigation" class="wrapper caption">
			<?php print $this->partial('_partial/manage_navigation.phtml',array('type' => 'administration','action' => 'profil')) ?>
		</div>
		<div id="content" class="wrapper">
			<?php print $this->layout()->content ?>
		</div>
	</div>
</div>

<div class="span-6 last">
	<div class="border">
		<div id="manage_panel" class="wrapper caption">
			<?php print $this->partial('_partial/manage_panel.phtml') ?>
		</div>
	</div>
</div>

<div class="clear"></div>

<div class="span-24 last">
	<?php  print $this->partial('_partial/foot.phtml') ?>
</div>
</div>
</body>
</html>
