<?php if(count($this->rowset)):?>
<h3 class="h-img specjalnosci">Specjalności</h3>

<ul class="item-list">
<?php foreach ((array) $this->rowset as $row):?>
	<li>
	<?php if (strlen($row['alias'])):?>
		<?php if ($row['subdomain']):?>
			<a href="<?php print $this->url(array('alias' => $row['alias']), 'catalogTypeWww')?>"><?php print $this->escape($row['name'])?></a>
		<?php else:?>
			<a href="<?php print $this->url(array('id' => $row['alias']), 'catalog-type')?>"><?php print $this->escape($row['name'])?></a>
		<?php endif;?>
	<?php else:?>
		<a href="<?php print $this->url(array('id' => $row['id']), 'catalog-type')?>"><?php print $this->escape($row['name'])?></a>
	<?php endif;?>
	</li>
<?php endforeach;?>
</ul>

<?php endif;?>