<div id="upper">
	<a class="prawnicykrakow" href=""><img src="css/newprawnicy/files/prawnicykrakow.png" width="160" height="22" alt="Prawnicy Kraków" /><strong>Prawnicy Kraków</strong></a>
	<ul class="upper-menu">
		<li class="home"><a href="">strona główna</a></li>
		<li class="contact"><a href="pl/strona/kontakt">kontakt</a></li>
	</ul>
</div>
<div id="navigation">
	<ul class="menu left">
		<li class="first home"><a href="<?php print $this->url(array(),'catalog-main',true) ?>">
			<span><strong>Strona główna</strong></span></a></li>
		<li class="list"><a href="<?php print $this->url(array(),'catalog-category',true) ?>">
			<span><strong>Spis</strong></span></a></li>
		<li class="search"><a href="<?php print $this->url(array(),'catalog-search',true) ?>">
			<span><strong>Wyszukiwarka</strong></span></a></li>
		<li class="last info"><a href="<?php print $this->url(array('url' => 'informacje-dla-prawnikow'),'page-page',true) ?>">
			<span><strong>Informacje dla prawników</strong></span></a></li>
	</ul>
	<ul class="menu right">
		<li class="last cosme"><a href="<?php print $this->url(array('alias' => 'instytucje'),'catalogWww-index',true) ?>">
			<span><strong>Instytucje</strong></span></a></li>
	</ul>
</div>


<?php if (count($messages = $this->FlashMessages())):?>
<ul id="flashMessages">
	<?php foreach ($messages as $message):?>
	<li><?php print $this->escape($message)?></li>
	<?php endforeach;?>
</ul>
<?php endif;?>