<div class="span-24 last options-holder">
	<?= $this->partial('_partial/common_head.phtml', array('controller' => 'certificate')) ?>
</div>

<hr class="bottom"/>

	<h2><?php print $this->row['name']?></h2>
	
	<?php if(!$this->promoted):?>
	<p style="color:#b00"><b>UWAGA:</b>Ta wizytówka nie jest w żadnym z pakietów!</p>
	<?php endif;?>

<hr class="bottom"/>

	<div class="span-2 options-holder">
		<h3>Akcje</h3>
	</div>
	
	<div class="span-21 last options-holder">
		
		<ul class="options-list top-left">
			<?php if(!$this->certificated):?>
			<li><a title="Włącz certyfikat" class="action true" href="<?php
		    	print $this->url(array('action' => 'changestate'));
		    ?>">Włącz certyfikat</a></li>
			<?php else:?>
			<li><a title="Wyłącz certyfikat" class="action false" href="<?php
		    	print $this->url(array('action' => 'changestate'));
		    ?>">Wyłącz certyfikat</a></li>
			<?php endif;?>
		</ul>
		
		<?php if($this->certificated):?>
		<ul class="options-list top-right">
		     <li><a class="action home" href="<?php
		    	print $this->url(array('id' => $this->row['id']), 'catalog-show');
		    ?>">Strona wizytówki</a></li>
		</ul>
		<?php endif;?>
		
	</div>

<?php 
	// jeżeli wpis nie jest certyfikowany nie wyświetlamy
	// opcji generowania certyfikatu
	if(!$this->certificated)
	{
		return;
	}
?>

<hr class="bottom"/>

<div class="clearfix">
	<div class="span-10 options-holder">
		<h3>Wygląd strony z certyfikatem &darr;</h3>
	</div>
	
	<div class="span-14 last options-holder">
		<ul class="options-list top-right">
			<li><a class="action content" href="<?php
		    	print $this->url(array('action' => 'show'));
		    ?>">Zobacz stronę certyfikatu</a></li>
			<li><a class="action attach" href="<?php
		    	print $this->url(array('action' => 'show', 'format' => 'pdf'));
		    ?>/fn/<?php print CATALOG_HOSTNAME?>-certyfikat-zaufania.pdf">Pobierz certyfikat w wersji PDF</a></li>
		</ul>
	</div>
</div>

<hr class="bottom"/>

<div style="margin: 10px auto; width: 400px; border: 3px solid #888;">
	<h1 style="text-align: center;">Certyfikat</h1>
	
	<p style="text-align: center; overflow: hidden;">
		<img style="float: none;" src="<?php print sprintf('%s/certyfikaty/%s/%s.png',
			$this->baseUrl(), CATALOG_TYPE, 'medium1')?>" alt="Certyfikat zaufania" /></p>
			
	<p style="text-align: center;">Redakcja infoportalu <?php print CATALOG_HOSTNAME ?></p>
	<p style="text-align: center;">na podstawie opinii przekazanych przez klientów</p>
	<p style="text-align: center;"><b>rekomenduje usługi gabinetu:</b></p>
	<p style="text-align: center;"><a href="<?php print $this->url(array('id' => $this->row['id']), 'catalog-show');?>"><?php print $this->row['name']?></a></p>
</div>

<p style="text-align: center;"> &uarr; Jest to wygląd abstrakcyjny - wizualizacja układu generowanego certyfikatu</p>

<hr class="bottom"/>

<div class="clearfix">
	<div class="span-10 options-holder">
		<h3>Rodzaje certyfikatów i informacje jak dodać do strony WWW &darr;</h3>
	</div>
	
	<div class="span-14 last options-holder">
		<ul class="options-list top-right">
			<li><a title="Pobierz certyfikat w wersji PDF" class="action attach" href="<?php
		    	print $this->url(array('format' => 'pdf'));
		    ?>/fn/<?php print CATALOG_HOSTNAME?>-jak-dodac-certyfikat.pdf">Pobierz informacje "jak dodać certyfikat" w wersji PDF</a></li>
		</ul>
	</div>
</div>

<hr class="bottom"/>

<?php $types = array('small','medium1','medium2','big')?>
<?php foreach ($types as $type):?>
<?php
$certyfikat = <<<ELP
<a href="%s" title="Certyfikat zaufania dla: %s"><img alt="Certyfikat zaufania dla: %s" src="%s"></a>
ELP;

$certyfikat = sprintf($certyfikat,
		$this->url(array('id'=> $this->row['id']),'catalog-show'),
		$this->escape($this->row['name']),
		$this->escape($this->row['name']),

		sprintf('%s/certyfikaty/%s/%s.png',
				$this->baseUrl(), CATALOG_TYPE, $type
		)
);
?>
<div class="span-15">
	<h6>Podgląd certyfikatu </h6>
	<?php print $certyfikat?>
</div>
<div class="span-7 last">
	<h6>Kod do wklejenia na stronę WWW</h6>
	<textarea rows="3" cols="30"><?php print $certyfikat;?></textarea>
</div>
<?php endforeach;?>