<?php 

	$this->getHelper('HeadTitle')->headTitle($this->row['title']);

	/* @var $meta Zend_View_Helper_HeadMeta*/
	$meta = $this->getHelper('HeadMeta');
	$meta->setName('title', $this->row['title']);
	$meta->setName('keywords', $this->row['title']);
	$meta->setName('description', $this->row['title']);
?>
<div id="agregation-display">
	<h1 class="head"><?php print $this->row['title']?></h1>
	
	<p class="back"><a rel="nofallow" href="<?php print $this->url(array(),'agregator-index')?>">&laquo; powrót do wszystkich wiadomości</a></p>
	
	<blockquote class="description"><p>
	<?php print $this->row['description']?>
	</p></blockquote>
	
	<p class="source"><em>Źródło:</em> <a href="<?php print $this->row['link']?>"><?php print $this->row['link']?></a><br/>
	<em>Dostawca:</em> <a href="<?php print $this->row['feed_link']?>"><?php print $this->row['feed_title']?></a></p>

	<p class="more"><a href="<?php print $this->row['link']?>" rel="nofallow">czytaj całość &raquo;</a></p>
</div>