<?php print $this->doctype(); ?>
<html>
<head>
	<?php
		print $this->headBase();
    	print $this->headMeta();
    	print $this->headTitle();
    	print $this->headScript();
    	print $this->headLink();
    	print $this->headStyle();
    ?>
</head>
<body>
<div id="wrapper">

	<div class="adv head">
		<script type='text/javascript'><!--// <![CDATA[
			OA_show(6);
		// ]]> --></script>
	</div>

	<div id="header">
		<?php print $this->partial('_partial/head.phtml')?>
	</div>

	<div id="content">
		<!-- Kolumna 1 - lewa -->
		<div class="col c1 wide">
			<div id="service-description" class="block-wrapper">
				<div class="block-main">
					<div class="block-bottom">
						<?php print $this->layout()->content ?>
					</div>
				</div>
			</div>
		</div>
		
		<!-- Kolumna 2 - prawa -->
		<div class="col">
			<div class="ads">
				<script type='text/javascript'><!--// <![CDATA[
					OA_show(7);
				// ]]> --></script>
			</div>
		</div>
	</div>

	<div class="doubleLine"></div>
	<div id="footer">
		<?php print $this->partial('_partial/foot.phtml')?>
	</div>

</div>
</body>
<?php print $this->inlineScript()?>
</html>
