<?php print $this->doctype(); ?>
<html>
<head>
	<?php
		print $this->headBase();
    	print $this->headMeta();
    	print $this->headTitle();
    	print $this->headScript();
    	print $this->headLink();
    	print $this->headStyle();
    ?>
</head>
<body>
<div id="wrapper">

	<div class="adv head">
		<!--/* OpenX Javascript Tag v2.8.2 */-->

		<script type='text/javascript'><!--//<![CDATA[
		   var m3_u = (location.protocol=='https:'?'https://ads.eu1.pl/www/delivery/ajs.php':'http://ads.eu1.pl/www/delivery/ajs.php');
		   var m3_r = Math.floor(Math.random()*99999999999);
		   if (!document.MAX_used) document.MAX_used = ',';
		   document.write ("<scr"+"ipt type='text/javascript' src='"+m3_u);
		   document.write ("?zoneid=6");
		   document.write ('&amp;cb=' + m3_r);
		   if (document.MAX_used != ',') document.write ("&amp;exclude=" + document.MAX_used);
		   document.write (document.charset ? '&amp;charset='+document.charset : (document.characterSet ? '&amp;charset='+document.characterSet : ''));
		   document.write ("&amp;loc=" + escape(window.location));
		   if (document.referrer) document.write ("&amp;referer=" + escape(document.referrer));
		   if (document.context) document.write ("&context=" + escape(document.context));
		   if (document.mmm_fo) document.write ("&amp;mmm_fo=1");
		   document.write ("'><\/scr"+"ipt>");
		//]]>--></script><noscript><a href='http://ads.eu1.pl/www/delivery/ck.php?n=aa8ca38e&amp;cb=INSERT_RANDOM_NUMBER_HERE' target='_blank'><img src='http://ads.eu1.pl/www/delivery/avw.php?zoneid=6&amp;cb=INSERT_RANDOM_NUMBER_HERE&amp;n=aa8ca38e' border='0' alt='' /></a></noscript>
	</div>

	<div id="header">
		<?php print $this->partial('_partial/head.phtml')?>
	</div>

	<div id="content">
		<div id="welcome">
			<div class="inner">
				<?php print $this->page('home-block','_partial/page.phtml')?>
			</div>
		</div>
		
		<!-- Kolumna 1 - lewa -->
		<div class="col c1 wide bg">
			<h2 class="znajdz_w_swojej_okolicy wide">Znajdź w swojej dzielnicy</h2>

			<?php
			print $this->catalogDistrictNavigation()
				->menu()->renderMenu(null, array(
					'ulClass'=> 'catalog-district-menu-2cols',
					'minDepth' => 1
				));
			?>

			<ins class="clear space"></ins>

			<a href="/stomatolodzy" class="button znm">zobacz na mapie</a>

			<ins class="clear space"></ins>
		</div>

		<!-- Kolumna 2 - prawa -->
		<div class="col c3">
			<?php print $this->catalogPremium()
							 //->setRandom(true)
							 ->setRowCount(6)
							 ->render('_partial/catalogPremium.phtml')?>

			<!--/* OpenX Javascript Tag v2.8.2 */-->

			<script type='text/javascript'><!--//<![CDATA[
			   var m3_u = (location.protocol=='https:'?'https://ads.eu1.pl/www/delivery/ajs.php':'http://ads.eu1.pl/www/delivery/ajs.php');
			   var m3_r = Math.floor(Math.random()*99999999999);
			   if (!document.MAX_used) document.MAX_used = ',';
			   document.write ("<scr"+"ipt type='text/javascript' src='"+m3_u);
			   document.write ("?zoneid=19");
			   document.write ('&amp;cb=' + m3_r);
			   if (document.MAX_used != ',') document.write ("&amp;exclude=" + document.MAX_used);
			   document.write (document.charset ? '&amp;charset='+document.charset : (document.characterSet ? '&amp;charset='+document.characterSet : ''));
			   document.write ("&amp;loc=" + escape(window.location));
			   if (document.referrer) document.write ("&amp;referer=" + escape(document.referrer));
			   if (document.context) document.write ("&context=" + escape(document.context));
			   if (document.mmm_fo) document.write ("&amp;mmm_fo=1");
			   document.write ("'><\/scr"+"ipt>");
			//]]>--></script><noscript><a href='http://ads.eu1.pl/www/delivery/ck.php?n=a2ac5096&amp;cb=INSERT_RANDOM_NUMBER_HERE' target='_blank'><img src='http://ads.eu1.pl/www/delivery/avw.php?zoneid=19&amp;cb=INSERT_RANDOM_NUMBER_HERE&amp;n=a2ac5096' border='0' alt='' /></a></noscript>

		</div>
	</div>

	<div class="doubleLine"></div>
	<div id="footer">
		<?php print $this->partial('_partial/foot.phtml')?>
	</div>

</div>
</body>
<?php print $this->inlineScript()?>
</html>
