<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<?php
	print $this->headBase();
    print $this->headMeta();
    print $this->headTitle();
    print $this->headScript();
    print $this->headLink();
    print $this->headStyle();
?>
</head>

<body>
   <div id="wrapper" class="home">
   		<?php print $this->partial('_partial/head.phtml')?>
   		
     	<div id="header" class="home">
        	<div class="txt">
	           <?php print $this->page('home-block','_partial/page.phtml')?>
            </div>
            <a href="" class="search-btn"><span>wyszukaj prawnika</span></a>
        </div>
        <div id="container">
        	<div class="column c33 bg-right"><div class="inner">
        	
        		<?php print $this->catalogType()
        						 ->render('_partial/catalogType.phtml')?>
        		
            </div></div>
            <div class="column c33 bg-right"><div class="inner">
            	<h3 class="h-img dzielnica">Wyszukaj w swojej dzielnicy</h3>
            	<?php
					print $this->catalogDistrictNavigation()
						->menu()->renderMenu(null, array(
							'ulClass'=> 'item-list',
							'minDepth' => 1
						));
				?>

                <a href="<?php print $this->url(array(),'catalog-search',true) ?>" class="more map"><span><strong>zobacz na mapie</strong></span></a>
            </div></div>
            <div class="column c33 pale">
            	<div class="inner">
            		<?php print $this->catalogPremium()
							 ->setRandom(true)
							 ->setRowCount(7)
							 ->render('_partial/catalogPremium.phtml')?>
            	
            	</div>
            	<b class="lt"></b><b class="lb"></b><b class="rt"></b><b class="rb"></b>
            </div>
        </div>
        <div id="footer">
        	<?php print $this->partial('_partial/foot.phtml')?>
        </div>
        
        <div id="bottom">
        	<?php print $this->partial('_partial/bottom.phtml')?>
        </div>
        
   </div>
</body>

<?php print $this->inlineScript()?>
</html>