<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<?php
	print $this->headBase();
    print $this->headMeta();
    print $this->headTitle();
    print $this->headScript();
    print $this->headLink();
    print $this->headStyle();
?>
</head>

<body>
   <div id="wrapper" class="home">
   		<?php print $this->partial('_partial/head.phtml')?>

        <div id="container">
        
        	<div class="column c66">
                <div id="search"><div class="inner">
                	<h3 class="h-img wyszukaj">Wyszukaj</h3>
                    <form action="<?php print $this->url(array(),'catalog-search');?>" method="get">
						<input type="text" class="in-text" name="q" value="<?php print $this->escape(strip_tags($this->q))?>" />
						<input type="submit" class="submit" value="szukaj" />
					</form>
                </div></div>
                
				<div class="inner">
                	<?php print $this->page('jak-szukac','_partial/page.phtml')?>
                </div>
                
				<?php print $this->inlineScript()->captureStart()?>
				var G_MAP_LAT = <?php print @$this->row['lat'];?>;
				var G_MAP_LNG = <?php print @$this->row['lng'];?>;
	
				showAddress('<?php print $this->escape(str_replace(array('-','"',"'"), ' ', $this->district)) ?>', 15);
				<?php print $this->inlineScript()->captureEnd()?>
                
                <?php print $this->layout()->content ?>
                 
            </div>
            <div class="column c33 sidebar">
            	<div class="pale">
            		<?php print $this->catalogPremium()
							 ->setRandom(true)
							 ->setRowCount(7)
							 ->render('_partial/catalogPremium.phtml')?>

                    <b class="lt"></b><b class="lb"></b><b class="rt"></b><b class="rb"></b>
                </div>
            </div>
        </div>

        <div id="footer">
        	<?php print $this->partial('_partial/foot.phtml')?>
        </div>

        <div id="bottom">
        	<?php print $this->partial('_partial/bottom.phtml')?>
        </div>
        
        <div id="hell">
        	<?php print $this->partial('_partial/hell.phtml')?>
        </div>
   </div>
</body>

<?php print htmlspecialchars_decode($this->inlineScript())?>
</html>