--
-- Zrzut danych tabeli `role_resource`
--

INSERT INTO `role_resource` (`id`, `name`) VALUES
(3, 'page_page'),
(2, 'admin_index'),
(4, 'user_resource'),
(5, 'user_access'),
(6, 'user_user'),
(7, 'user_admin'),
(8, 'user_auth'),
(9, 'default_error'),
(10, 'default_index'),
(18, 'page_index'),
(86, 'admin_install'),
(20, 'language_admin'),
(21, 'page_block'),
(34, 'default_actions'),
(36, 'user_role'),
(37, 'page_blocks'),
(44, 'user_index'),
(48, 'system_admin'),
(49, 'system_settings'),
(50, 'system_modules'),
(52, 'catalog_catalog'),
(53, 'catalog_admin'),
(54, 'catalog_index'),
(55, 'catalog_district'),
(56, 'catalog_type'),
(57, 'catalog_service'),
(58, 'catalog_servicecost'),
(59, 'catalog_image'),
(64, 'catalog_management'),
(65, 'catalog_promotype'),
(66, 'catalog_promotime'),
(67, 'catalog_options'),
(68, 'catalog_optionshas'),
(69, 'catalog_time'),
(70, 'catalog_staff'),
(71, 'catalog_staffhas'),
(72, 'advertising_type'),
(73, 'advertising_block'),
(74, 'advertising_client'),
(75, 'advertising_advertise'),
(76, 'advertising_admin'),
(78, 'catalog_list'),
(79, 'catalog_search'),
(81, 'catalog_time2'),
(82, 'catalog_site'),
(83, 'catalog_siteframe'),
(84, 'catalog_mail'),
(85, 'system_update');
