CREATE TABLE  `catalog` (
  `id` bigint(20) NOT NULL auto_increment,
  `user_id` int(11) NOT NULL COMMENT 'Użytkownik',
  `name` varchar(255) NOT NULL COMMENT 'Nazwa',
  `city` varchar(60) NOT NULL default 'Kraków' COMMENT 'Miasto',
  `adress` varchar(255) NOT NULL COMMENT 'Adres',
  `catalog_district_id` int(11) NOT NULL COMMENT 'Dzielnica',
  `lat` float(10,6) NOT NULL COMMENT 'Współrzędna X',
  `lng` float(10,6) NOT NULL COMMENT 'Współrzędna Y',
  `catalog_type_id` int(11) NOT NULL COMMENT 'Typ obiektu',
  `meta_title` varchar(255) character set utf8 NOT NULL,
  `meta_description` varchar(255) character set utf8 NOT NULL,
  `meta_keywords` varchar(255) character set utf8 NOT NULL,
  `description` mediumtext NOT NULL COMMENT 'Opis',
  `info` mediumtext NOT NULL COMMENT 'Dodatkowe informacje',
  `contact` mediumtext character set utf8 collate utf8_bin NOT NULL,
  `www` varchar(70) default NULL COMMENT 'Strona WWW',
  `email` varchar(55) default NULL COMMENT 'Adres Email',
  `phone` varchar(16) character set utf8 collate utf8_bin default NULL,
  `postcode` varchar(6) default NULL COMMENT 'Kod pocztowy',
  `catalog_image_id` bigint(20) default NULL COMMENT 'Główna grafika',
  `catalog_option1_id` tinyint(4) default NULL,
  `catalog_option2_id` tinyint(4) default NULL,
  `catalog_option3_id` tinyint(4) default NULL,
  PRIMARY KEY  (`id`),
  KEY `new_index` USING BTREE (`catalog_district_id`,`catalog_type_id`),
  KEY `xy` (`lat`,`lng`),
  KEY `options` (`catalog_option1_id`,`catalog_option2_id`,`catalog_option3_id`),
  KEY `phone` (`phone`)
) ENGINE=MyISAM AUTO_INCREMENT=101 DEFAULT CHARSET=latin1
