<?php 
if (count($this->row)) {
	if (strlen($this->row['meta_title']) > 1) {
		$this->headTitle($this->row['meta_title']);
	}
	if (strlen($this->row['meta_description']) > 1) {
		$this->headMeta($this->row['meta_description'], 'description');
	}
	if (strlen($this->row['meta_keywords']) > 1) {
		$this->headMeta($this->row['meta_keywords'], 'keywords');
	}
}
?>
<?php print $this->partialLoop('_partial/partialLoopCatalogList.phtml','catalog', (array) $this->rowset)?>
<?php
if (null != $this->paginator) {
	print $this->paginationControl($this->paginator,
                             'Sliding',
                             '_partial/newPagination.phtml');
}
?>