<?php foreach ((array) $this->rowset as $row):?>
<?php if (strlen(@$row['alias']) > 1):?>
	<?php if ($row['subdomain']):?>
		<a href="<?php print $this->url(array('alias' => $row['alias']), 'catalogTypeWww')?>"><?php print $this->escape($row['name'])?></a>
	<?php else:?>
		<a href="<?php print $this->url(array('id' => $row['alias']), 'catalog-type')?>"><?php print $this->escape($row['name'])?></a>
	<?php endif;?>
<?php else:?>
<a href="<?php print $this->url(array('id' => $row['id']), 'catalog-type')?>"><?php print $this->escape($row['name'])?></a>
<?php endif;?>
<?php endforeach;?>
