<?php print $this->form?>

<?php if (!count($this->rowset)):?>
<p class="msg-info">Nie został dodany personel</p>
<?php else:?>

<table>
    <col width="120" />
    <col width="*%" />
    <col width="150" />
    <col width="100" />
    <thead>
        <tr>
            <th>Miniaturka</th>
            <th colspan="3">Imię i nazwisko</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($this->rowset as $row):?>
        <tr>
            <td><img src="<?php print $this->url(array('file'=>$row->image),'catalogImageStaff');?>" /></td>
            <td>
                <a class="action edit" href="<?php print $this->url(array(
                   'action'=>'staffupdate',
                   'staff_id' => $row->id))?>"><?php print $row->fullname?></a>
            </td>
            <td>
                <a class="action edit" href="<?php print $this->url(array(
                   'action'=>'staffupdate',
                   'staff_id' => $row->id))?>">Edytuj</a>
            </td>
            <td>
                <a  class="action delete"
                    onclick="return confirm('Czy usunąć osobe?');"
                    href="<?php print $this->url(array(
                    'action'=>'staffdelete',
                    'staff_id' => $row->id))?>">Usuń</a>
            </td>
        </tr>
        <?php endforeach;?>
    </tbody>
</table>
<?php endif;?>