<?php print $this->doctype(); ?>
<html>
<head>
	<?php
		print $this->headBase();
    	print $this->headMeta();
    	print $this->headTitle();
    	print $this->headScript();
    	print $this->headLink();
    	print $this->headStyle();
    ?>
</head>
<body>
<div id="wrapper">

	 <div id="wrapper" class="home">
   		<div id="upper">
       		<a class="fryzjerzykrakow" href=""><img src="css/<?php print CATALOG_TYPE ?>/files/fryzjerzykrakow.png" width="157" height="22" alt="Fryzjerzy Kraków" /><strong>Fryzjerzy Kraków</strong></a>           
        </div>
     </div>
	
	<div id="container">
		<div class="column c66">
			<div class="inner">
				<h1>Fryzjer Kraków</h1>

				<div class="info">
					<span class="icon"></span>
					Już wkrótce, największy infoportal fryzjerzy w Krakowie zaprezentuje pełną bazę salonów fryzjerskich, salonów kosmetycznych znajdujacych się na terenie Krakowa.  
				</div>

				<h2>Fryzjerzy w Krakowie - możliwości</h2>

                <ol class="with-numbers">
	                <li>
	                	<span class="nr nr-circle">1</span>
	                	Znajdz salon fryzjerski, gabinet kosmetyczny blisko siebie, <b>zlokalizujemy go na mapie dla Ciebie!</b>
	                </li>
	                <li>
	                	<span class="nr nr-circle">2</span>
	                	Wpisz jedno słowo, usługę, ulicę, dzielnicę, dzodzinę, imię lub nazwisko fryzjera, a my znajdziemy go dla Ciebie.
	                </li>
	                <li>
	                	<span class="nr nr-circle">3</span>
	                	<b>Galeria fryzór</b> - sprawdz, jakie uczesanie jest najmodniejsze, wybierz która fryzuca do Ciebie pasuje i zobacz w jaki salonie fryzjerskim uzyskasza taki efekt!
	                </li>
				</ol>
				
				<p>Zapraszamy równiesz do zobaczenia:</p>
				
				<ul>
	                <li>
	                	Największy profesjonalny infoportal lekarzy w Krakowie zaprasza na stronę internetową:
						<a href="http://lekarze.krakow.pl" title="Lekarze w Krakowie">Lekarz Kraków</a>
	                </li>
	                <li>
	                	Największy profesjonalny infoportal stomatologów i dentystów w Krakowie zaprasza na stronę internetową:
						<a href="http://lekarze.krakow.pl" title="Stomatolodzy w Krakowie">Stomatolog Kraków</a>
	                </li>
	                <li>
	                	Największy profesjonalny infoportal lekarzy weterynarii w Krakowie zaprasza na stronę internetową:
	                	<a href="http://weterynarze.krakow.pl" title="Weterynarz w Krakowie">Weterynarz Kraków</a>
	                </li>
				</ul>
                
			</div>
		</div>
    </div>

</div>
<?php print htmlspecialchars_decode($this->inlineScript())?>
</body>
</html>