<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<?php
	print $this->headBase();
    print $this->headMeta();
    print $this->headTitle();
    print $this->headScript();
    print $this->headLink();
    print $this->headStyle();
?>
</head>

<body>
   <div id="wrapper" class="home">
   		<?php print $this->partial('_partial/head.phtml')?>

		<div id="loader">Wczytuję, prosze czekać..</div>
   		
        <div id="container">
        
        	<div class="column c66">
                
                <?php print $this->layout()->content ?>
                 
            </div>
            <div class="column c33 sidebar">
            	<div class="inner">
            		<?php print $this->catalogType()
	        						 ->render('_partial/catalogType.phtml')?>

	            	<h3 class="h-img dzielnice">Wyszukaj w swojej dzielnicy</h3>
	            	<?php print $this->catalogDistrictTree()
								 ->setActiveUrl($this->district)
								 ->toString()?>
	            
				</div>
            </div>
        </div>

        <div id="footer">
        	<?php print $this->partial('_partial/foot.phtml')?>
        </div>

        <div id="bottom">
        	<?php print $this->partial('_partial/bottom.phtml')?>
        </div>
   </div>
</body>

<?php print htmlspecialchars_decode($this->inlineScript())?>
</html>