<?php print $this->doctype(); ?>
<html>
<head>
	<?php
		print $this->headBase();
    	print $this->headMeta();
    	print $this->headTitle();
    	print $this->headScript();
    	print $this->headLink();
    	print $this->headStyle();
    ?>
</head>
<body>
<div id="wrapper">

	<div class="adv head">
		<script type='text/javascript'><!--// <![CDATA[
			OA_show(6);
		// ]]> --></script>
	</div>

	<div id="header">
		<?php print $this->partial('_partial/head.phtml')?>
	</div>

	<div id="content">
		<div id="welcome">
			<div class="inner">
				<?php print $this->page('home-block','_partial/page.phtml')?>
			</div>
		</div>
		
		<!-- Kolumna 1 - lewa -->
		<div class="col c1 wide bg">
			<h2 class="znajdz_w_swojej_okolicy wide">Znajdź w swojej dzielnicy</h2>

			<?php
			print $this->catalogDistrictNavigation()
				->menu()->renderMenu(null, array(
					'ulClass'=> 'catalog-district-menu-2cols',
					'minDepth' => 1
				));
			?>

			<ins class="clear space"></ins>

			<a href="/stomatolodzy" class="button znm">zobacz na mapie</a>

			<ins class="clear space"></ins>
			
			<div class="ads">
				<script type='text/javascript'><!--// <![CDATA[
					OA_show(8);
				// ]]> --></script>
			</div>
		</div>

		<!-- Kolumna 2 - prawa -->
		<div class="col">
			<div class="c3">
				<?php print $this->catalogPremium()
								 ->setRandom(true)
								 ->setRowCount(5)
								 ->render('_partial/catalogPremium.phtml')?>
			</div>
			<div class="ads">
				<script type='text/javascript'><!--// <![CDATA[
					OA_show(19);
				// ]]> --></script>
			</div>
		</div>
	</div>

	<div class="doubleLine"></div>
	<div id="footer">
		<?php print $this->partial('_partial/foot.phtml')?>
	</div>

</div>
</body>
<?php print $this->inlineScript()?>
</html>
