<?php if ($this->pageCount): ?> 
<div class="paginationControl">
<!-- Previous page link --> 
<?php if (isset($this->previous)): ?> 
 <a href="?page=<?php print $this->previous;?>">&laquo; Poprzedni</a>  
<?php else: ?> 
  <span class="disabled">&laquo; Poprzedni</span> 
<?php endif; ?> 

<!-- Numbered page links -->
<?php foreach ($this->pagesInRange as $page): ?> 
  <?php if ($page != $this->current): ?>
    <a href="?page=<?php print $page;?>"><?= $page; ?></a> 
  <?php else: ?>
    <span class="selected"><?= $page; ?></span>
  <?php endif; ?>
<?php endforeach; ?>

<!-- Next page link --> 
<?php if (isset($this->next)): ?> 
  <a href="?page=<?php print $this->next;?>">Następny &raquo;</a>
<?php else: ?> 
  <span class="disabled">Następny &raquo;</span>
<?php endif; ?>
</div>
<?php endif; ?>